Import dependencies

In [37]:
import openai
import pandas as pd

from qdrant_client import QdrantClient
from qdrant_client import models
from qdrant_client.models import VectorParams,Distance,SparseVectorParams,Modifier,PayloadSchemaType,PointStruct,Document,Prefetch,FusionQuery

Create Qdrant Collections for hybrid search

In [38]:
qdrant_client= QdrantClient(url="http://localhost:6333")

In [39]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-01-hybrid-search",
    vectors_config={
         "text-embedding-3-small":VectorParams(size=1536,distance=Distance.COSINE)
        },
        sparse_vectors_config={
            "bm25":SparseVectorParams(modifier=Modifier.IDF)
        }


)

True

In [40]:
qdrant_client.create_payload_index(
    collection_name="Amazon-items-collection-01-hybrid-search",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

Embedding Functions

In [41]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [42]:
def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i + batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter * batch_size} of {len(text_list)}")
        counter += 1
    
    return all_embeddings

Read the sampled dataset with  Amazon inventory data

In [43]:
df_items=pd.read_json("../../data/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [44]:
df_items.head(5)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,AMAZON FASHION,3 Pack Fitbit Luxe Bands Compatible with Fitbi...,4.4,261,"[Buckle closure, 【Applicable Model】Meliya repl...",[Meliya Fitbit Luxe wristbands make you more f...,8.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Meliya,"[Electronics, Wearable Technology, Arm & Wrist...","{'Date First Available': 'September 19, 2022',...",B0BFQH6535,NaN,NaN,NaN
1,All Electronics,Charger Charging Cable Cord fits for Beats by ...,4.2,180,[[Perfect compatibility]: Compatible with Beat...,[],11.98,[{'thumb': 'https://m.media-amazon.com/images/...,[],FlickerStar,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '4.33 x 2.05 x 1.54 inc...,B09TBF91FL,NaN,NaN,NaN
2,All Electronics,"Wireless Keyboard and Mouse Combo, Giecy 2.4G ...",4.4,135,[【Comfortable Wireless Keyboard Mouse Combo】 w...,[],36.98,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Comfortable Wireless Keyboard Mous...,Giecy,"[Electronics, Computers & Accessories, Compute...",{'Product Dimensions': '16.9 x 4.9 x 2.5 inche...,B0C36WD52F,NaN,NaN,NaN
3,Cell Phones & Accessories,HoneyAKE Case for Google Pixel Buds A-Series C...,3.9,126,[For Google Pixel Buds A-Series 2021 Case for ...,[],10.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Solid and not bully', 'url': 'http...",HoneyAKE,"[Electronics, Headphones, Earbuds & Accessorie...","{'Brand': 'HoneyAKE', 'Item model number': 'GU...",B09XH2TK3R,NaN,NaN,NaN
4,Computers,"2 Pack LCD Writing Tablet 12 Inch for Kids,Toy...",4.4,752,[Color drawing boards: We firmly believe that ...,[],19.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Newest 2 Pack LCD writing tablet f...,LEYAOYAO,"[Electronics, Computers & Accessories, Compute...","{'Standing screen display size': '12 Inches', ...",B0BFR7JRQS,NaN,NaN,NaN

Preprocess Titles and features

In [45]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [46]:
def first_largeimage(row):
    return row['images'][0].get("large","")

In [47]:
df_items["preprocessed_description"] = df_items.apply(preprocess_description, axis=1)
df_items["image"] = df_items.apply(first_largeimage, axis=1)

In [48]:
list(df_items["image"].items())[0]

(0, 'https://m.media-amazon.com/images/I/411HNQcSv+L._AC_.jpg')

Sample 50 items from the dataset

In [49]:
df_sample = df_items.sample(n=50, random_state=42)

In [50]:
df_data_to_embed = df_items[["preprocessed_description", "image", "rating_number", "price", "average_rating","parent_asin"]]

In [51]:
df_data_to_embed.head(5)

,preprocessed_description,image,rating_number,price,average_rating,parent_asin
0,3 Pack Fitbit Luxe Bands Compatible with Fitbi...,https://m.media-amazon.com/images/I/411HNQcSv+...,261,8.99,4.4,B0BFQH6535
1,Charger Charging Cable Cord fits for Beats by ...,https://m.media-amazon.com/images/I/41m9Y41SAf...,180,11.98,4.2,B09TBF91FL
2,"Wireless Keyboard and Mouse Combo, Giecy 2.4G ...",https://m.media-amazon.com/images/I/41tv9QvDaZ...,135,36.98,4.4,B0C36WD52F
3,HoneyAKE Case for Google Pixel Buds A-Series C...,https://m.media-amazon.com/images/I/41zgEuCGnL...,126,10.99,3.9,B09XH2TK3R
4,"2 Pack LCD Writing Tablet 12 Inch for Kids,Toy...",https://m.media-amazon.com/images/I/51Veurn-wF...,752,19.99,4.4,B0BFR7JRQS

In [52]:
data_to_embed=df_data_to_embed.to_dict(orient="records")

In [53]:
data_to_embed

[{'preprocessed_description': '3 Pack Fitbit Luxe Bands Compatible with Fitbit Luxe Women Men, Soft Silicone Wristband Replacement Strap for Fitbit Luxe/Luxe Special Edition Fitness Tracker Buckle closure 【Applicable Model】Meliya replacement wristbands Specially Designed for Fitbit Luxe / Fitbit Luxe Special Edition Only, NO Fitbit Luxe tracker included. 【Seamless Match】Fits as good as original Fitbit Luxe band. Simple to install and remove, NO tools required! The end of the band has a lug, which fit your Fitbit Luxe smart watch in place and locked precisely & securely. 【Premium Waterproof Material】Made from flexible high-quality elastomer, sweatproof & waterproof. Prevents skin from irritation, soft, lightweight and durable, very comfortable to wear. 【Available in Two Sizes】Small size: for 5.5"-7.3" wrists. Large size: for 6.7"-8.3" wrists 【After-sales Service】If you have any dissatisfaction with replacement bands for Fitbit Luxe from Meliya Store, please contact us via Amazon e-mail. We will reply to you ASAP.',
  'image': 'https://m.media-amazon.com/images/I/411HNQcSv+L._AC_.jpg',
  'rating_number': 261,
  'price': 8.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BFQH6535'},
 {'preprocessed_description': 'Charger Charging Cable Cord fits for Beats by Dr Dre Studio Solo 3 2, Powerbeats 3 2, Beats Studio Buds, Fit Pro, Flex Wireless Headphone Earbuds Earphone Adapter Power Supply (USB Type C & Micro) [Perfect compatibility]: Compatible with Beats Studio Buds, Beats Flex, Beats Fit Pro, Beats by dr dre Studio 2 3, Beats by dr dre Solo 2 3, Beats by dr dre Powerbeats 2 3, Beats Pill 2.0 Speakers. [Portable & Multifunctional]: The compact charger allows you to easily carry it and use it with a power bank. The two-in-one design of USB-C and USB-Micro brings you a wider range of usability. [Safety smart]: Built-in emergency protection mechanism with short circuit, over current, over voltage, over temperature protection. [Durable life]: The product has passed FCC/UL testing and certification, and the cable has undergone 10000+ bending violence tests. The charger has undergone rigorous drop and flame tests. [Lifetime friendly customer service]: If you are not satisfied with the product, please contact us!',
  'image': 'https://m.media-amazon.com/images/I/41m9Y41SAfL._AC_.jpg',
  'rating_number': 180,
  'price': 11.98,
  'average_rating': 4.2,
  'parent_asin': 'B09TBF91FL'},
 {'preprocessed_description': 'Wireless Keyboard and Mouse Combo, Giecy 2.4G Full-Sized Ergonomic Keyboard Mouse, Adjustable Ergonomic Full Size Keyboard USB Keyboard and Mouse, Plug & Play for Computer/Laptop/Windows/Mac 【Comfortable Wireless Keyboard Mouse Combo】 wireless keyboard mouse combo has a comfortable touch and typing feel, this wireless keyboard design with palm rest and folding holder that can protect your wrists from injury even when typing for a long time. NOTE: THE USB RECEIVER IS IN THE BATTERY COMPARTMENT OF THE MOUSE, YOU CAN FIND IT WHEN OPEN THE MOUSE BATTERY COVER. 【2.4G Stable Wireless Connection】This wireless keyboard and mouse combo share the same USB receiver, no need to take upadditional USB ports (Also the wireless keyboard and mouse can also be used separately). wireless keyboard and mouse Just plug USB receiver in device and turn keyboard on then enjoy no-lag play without any driver or pairing. 【Automatic Power Saving Function】The wireless keyboard and mouse combo has the function of automatically entering the power-saving state. When you stop using the keyboard for more than 15 minutes, stop using the mouse for more than 15 minutes, they will enter sleep mode respectively to save power. This feature greatly extends the battery life, you can click any button to activity the device. 【Adjustable Ergonomic Design computer keyboards】Our Full-Size Keyboard is designed with ergonomics in mind, allowing you to type comfortably for hours on end. 【Universal Compatibility】Our wireless computer keyboard is fully compatible with all major operating systems, including Windows, macOS, and Linux. promises that OUR PRODUCT HAVE A 12-MONTH FREE AFTER-SALES SERVICE. as long as you contact us, we will help you solve all problems.',
  'image': 'https://m.media-amazon.com/images/I/41tv9QvDaZL._AC_.jpg',
  'rating_number': 135,
  'price': 36.98,
  'average_rating': 4.4,
  'parent_asin': 'B0C36WD52F'},
 {'preprocessed_description': "HoneyAKE Case for Google Pixel Buds A-Series Case 2021, Protective Cover for Google Pixel Buds A with Keychain Clip Security Lock Shockproof Google Pixel Buds A Earbuds Case Women Men Black Blue For Google Pixel Buds A-Series 2021 Case for Women Men: This charging case compatible with Google Pixel Buds A-Series 2021 wirless earphone. (NOTICE: Google Pixel Buds A device NOT included). HoneyAKE offers 12-month warranty for replacement or full refund without return the case. Metal Carabiner Design: This Google Pixel Buds A case cover with a carabiner. The carabiner can be hung on your belt, bag or key. And cover your new Google Pixel Buds A cover and fit well to provide secure 360° all-round protection. Security Lock Design: The Google Pixel Buds A-Series case can be fully opened up to 90°, very easy to take out and put in your compatible Google Pixel Buds A. And earphone shell is composed of upper and lower shells, adopts a split structure, and has a safety lock function on the front. Press the front locking button to automatically open the top cover. Support Wireless Charging: This Case fit for google pixel buds a-series case cover fully supports wireless charging without any interference and the LED indicator is visible. It is also convenient to charge the Pixel Buds A Charging cable without removing the case. Perfect Gift: This Cover for Google Pixel Buds A 2021 case for girls, women and men with Keychain ring holder is a great gift for your friends, girlfriend or familys on Birthday, Christmas, Thanksgiving, Halloween, Valentine's Day or other special days.",
  'image': 'https://m.media-amazon.com/images/I/41zgEuCGnLL._AC_.jpg',
  'rating_number': 126,
  'price': 10.99,
  'average_rating': 3.9,
  'parent_asin': 'B09XH2TK3R'},
 {'preprocessed_description': '2 Pack LCD Writing Tablet 12 Inch for Kids,Toys for 3 4 5 6 7 8 9 Year Old Girls Boys,LEYAOYAO Colorful Drawing Pad Doodle Board,Travel Learning Birthday Gift for 3 Age+ Toddler (Pink+Blue) Color drawing boards: We firmly believe that LEYAOYAO can make thousands of children write "I ♥ Mom" on the drawing board, then we will succeed. LCD writing tablet adopts the latest liquid crystal pressure-sensitive technology, which produces lines of different thicknesses according to the strength of your push. When boys and girls write, draw, and graffiti, different colors will appear on the drawing tablets. 2 pack sharing: 2 writing tablets 12Inch(1 Blue and 1 Pink). The electronic drawing tablet has one-key clear button, can be erased and written more than 100,000 times. magnetic learning toys for toddlers tablet.There is no mess of paper, crayons, markers or chalk at home.The key lock effectively prevents accidental clearing, and the screen can be erased when the writing pad unlocking. Multi-Purpose: our doodle board suitable for kids drawing,graffiti,painting,draft ,note taking,learning and scrawl at home ,school or travel etc.Toys for 3 4 5 6 7 8 9 years old girls boys. Lightweight and Portable: Made of high-quality plastic material, weighs only 280 grams, is easy to carry and travel in scheduler, briefcase or backpack, suitable for multiple occasions: living room, car,restaurant, plane,outdoor places. The writing tablet is waterproof and anti-fall, no need to worry about accidental dropping and liquid pouring on the screen. Best gifts: the best learning toy for kid. It can be an educational toy for preschoolers. It can be a travel toy for long drives and road trips. A parent-pick gift for kids 3+ age girl and boy on Valentine\'s day, back to school, homeschool,Easter,birthday,Children\'s Day,Thanksgiving Day, Christmas and any occasions!',
  'image': 'https://m.media-amazon.com/images/I/51Veurn-wFL._AC_.jpg',
  'rating_number': 752,
  'price': 19.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BFR7JRQS'},
 {'preprocessed_description': "Video Conference Lighting for Laptop&Computer, Webcam Light for Streaming, Zoom Lighting for Computer, 3 Light Modes, 10 Brightness Adjustable, Metal Tripod for Self Broadcast,Live Streaming 【Newly Designed Multifunctional Video Conference Light】Show your best image in your online activities through this video conference light. It can significantly enhance your image in video conferences, online courses, live streaming, and other scenes through exquisite lighting, helping you showcase your confident and excellent side to others.At the same time, it also serves as a light source to provide corresponding lighting for reading, sleeping, resting, and makeup. 【Three Type Holder】Unique metal tripod made of frosted metal, which is more sturdy and stable than plastic. It is divided into two adjustable sections and easy to store;There are also two special clips：Adjustable clip has a greater up and down movement angle, making it more stable to use;The composite clip is more versatile, especially when the computer display screen is thicker, it can achieve better adaptation. You can choose the appropriate usage method according to your needs. 【3 Light Modes&10-Level Brightness】There are three lighting modes available: natural light (suitable for work, video conferencing), white light (high brightness, suitable for dim environments), and warm light (suitable for bedroom, restaurant). The color temperature of 2500-9000K is much higher than the market average of 6500K, providing higher brightness and more options.10-Level brightness adjustments means you can choose the appropriate brightness based on your needs using the remote control. 【Asymmetric Light Source Design&USB-powered&Space-saving】The 45° asymmetric light source design reduces reflections from computer screens, protecting your eyes and vision. The light is powered via a USB Type-C interface, eliminating concerns about battery depletion during use. With its slim and compact dimensions of 11.02 * 1.6 * 0.3in, it doesn't take up any desktop space, enhancing work efficiency. 【Packaging Content & After-Sales Guarantee】Package content: video conference light * 1,Metal tripod * 1, anti-skid clip * 1, USB remote controller * 1, instruction manual * 1.Our shop guarantees a one-year warranty. If you have any quality problems, please contact us, and we will help you solve them.",
  'image': 'https://m.media-amazon.com/images/I/418A32JtwKL._AC_.jpg',
  'rating_number': 102,
  'price': 29.99,
  'average_rating': 4.2,
  'parent_asin': 'B0B1TZ8B5D'},
 {'preprocessed_description': 'LFS Portable Bluetooth Shower Speaker, Waterproof Outdoor Wireless Speaker, Ultra-Long Play Time 15 Hours, TWS Pairing, Suitable for Home, Pool, Beach, Boating, Hiking, Camping TWS Dual Stereo: updated sound with 10W high stereo power through two Bluetooth speakers connected together! speakers bluetooth wireless has crystal clear sound and rich, full bass, you will be blown away by the HD quality sound Bluetooth version 5.0: Portable wireless Bluetooth speaker uses advanced Bluetooth technology to provide fast connectivity as well as greater wireless range and more stable Bluetooth connection for all Bluetooth devices. Such as cell phones, tablets, laptops, computers, Macbooks, MP3 players, etc Super long playing time: LFS portable Bluetooth speaker has a built-in 1500mAh rechargeable lithium battery, Bluetooth speaker can be used up to 15 hours, so you can enjoy music from morning to night, never stop Waterproof and Dustproof: Bluetooth waterproof outdoor speaker ensures dustproof, waterproof, shockproof, rainproof and snowproof, perfect for hiking, rafting, boating, swimming, kayaking and showering, etc. Bring our Bluetooth speaker and let it be your good companion also let you be a travel rocker Lightweight and portable small size: portable wireless bluetooth speaker wears a lanyard and has a built-in microphone that makes it easy to take calls via bluetooth mode. bluetooth speakers modern design makes it a great gift choice for any occasion, at a friends party, going camping outdoors with family and friends, etc',
  'image': 'https://m.media-amazon.com/images/I/51LM9xeP22L._AC_.jpg',
  'rating_number': 297,
  'price': 13.99,
  'average_rating': 4.4,
  'parent_asin': 'B0CF589N1T'},
 {'preprocessed_description': 'DTTOCASE iPad 10th Generation Kickstand Protective Case 2022,iPad 10.9 Inch Cover with Matte Frosted Shockproof Back [Anti-Fingerprint,Anti-Scratch,Support Touch ID,Camera Protection]-Rose Gold ⭐【Compatibility Model】This Matte Frosted Case is compatible with Apple iPad 10th Generation 10.9 inch Model Number:A2757/A2777/A2696 (2022 released)(2022 released), Not compatible with any other iPad devices. ⭐【Three-in-One Cover】Offers the difference by Ultra Hybrid protection Design, Hard Matte Frosted PC back provides strong support, Anti-Fingerprint and Anti-Scratch.and Soft TPU frame protects your iPad from shocks, drops, and impacts. Front Screen Protector cover prevents scratches without compromising sensitivity. ⭐【 Slim and Stylish 】Precise cutouts for all buttons and ports with just 0.6-inches Thickness, Minimalist shape,Matte frosted translucent back, and beautiful colors bring you to ease and comfort at any time. ⭐【Multiple Function】This iPad case has Pencil Holder to support Touch ID, Camera Protection, Two Kickstand Angle - gives you 2 different comfortable angles. ⭐【Lifetime Warranty 】DTTOCASE Offers Lifetime Free Replacement for Your IPad Case. (Needs to be activated within 30 days of purchasing) Your Satisfaction Is Our Top Concern.',
  'image': 'https://m.media-amazon.com/images/I/41lR5hanUjL._AC_.jpg',
  'rating_number': 192,
  'price': 16.99,
  'average_rating': 4.5,
  'parent_asin': 'B0BJNWGH39'},
 {'preprocessed_description': '2Pack Security Cameras Outdoor Wireless, 2K Surveillance Camera with Night Vision, Motion Detection, IP66 Waterproof, Cloud Storage, 24/7 Recordings, Live View, Work with Alexa Google Assitant 24/7 continuous recordings & IP66 waterproof - Watching home security, day and night, with 24/7 live video.Rraycom Indoor Cam plugs into power, never have to worry about dead batteries. Security camera with IP66 ultra-high waterproof performance can connect to 2.4 Ghz wifi, support installation anywhere (need plug in) 2K QHD clear resolution & Night vision - With 3MP ultra-high definition, you can see clearer details than 1080P cameras. A stunning night vision security camera allows you to get a clear picture even in total darkness. Smart AI recognition & Custom delineated area - Wireless cameras for home security with advanced smart AI detection can easily distinguish humans, vehicle or animal, you can also manually define detection areas to improve alert accuracy and reduce unnecessary reminders. Work with Alexa and Google Assistant - The Rraycom wireless outdoor camera support voice control via Alexa/Google Assistant-enabled device. Hands-free with Alexa by saying, "Alexa, show me the living room" to view a live stream via the echo show.---Note: The outdoor camera does not support a two-way audio function. 30-days Free Trial of Cloud Service - Enjoy a 30-days free trial of the “meshare” 7-days cloud recording plan. With the plan, you can review, save, and share footage at any time. You can subscribe to the Premium plan Or Platinum plan of the cloud service after the cloud service trial expired.',
  'image': 'https://m.media-amazon.com/images/I/31b-FdqAmyL._AC_.jpg',
  'rating_number': 102,
  'price': 36.99,
  'average_rating': 3.9,
  'parent_asin': 'B0BK9B5PWX'},
 {'preprocessed_description': "Bluetooth Headphones Wireless Earbuds 50Hrs Playtime with Wireless Charging Case Dual LED Display Ear Buds Waterproof Immersive Stereo in-Ear Earphones with Mic for Phone TV Computer Android White 1. Dual LED Power Display: Bluetooth headphones with dual battery display show the remaining juice of charging case by the number on the screen, and the charging status of ear buds by up and down of LED bar. When the wireless earbuds are charging, the LED bars flash from 1st to 4th grid repeatedly, and go out after fully charged. Also you can easily know the battery consumption on both wireless headphones and the charging case so you can master the best time to charge it. 2. Up to 50Hrs Playtime with Wireless Charging Case: Each bluetooth earbud lasts around 5 hours on a single charge for normal use (100% volume), more than 50 hours total listening time with the portable charging case, which can be charged via the included USB-C cable or wirelessly with any QI-certified charging mat (not included). These wireless headphones bluetooth have enough battery to last all day and all night. Keep your own private concert going for as long as you can keep up. 3. Hi-Fi Stereo Sound & Crystal Clear Call: Supported by a powerful 12mm speaker driver unit and semi-in-ear acoustic structure to produce sound with strong bass, clear mids, and bright treble. Unique chamber acoustic design balances the internal and external air pressure to avoid sound loss, making sure the sound stable and penetrating to provide clear voice detection even in noisy environments. Enjoy your personal space whether you're indoors, outdoors, work or sports. 4. One-step Pairing & Smart Touch Control: Built in hall switch, bluetooth earphones will auto power on and connect with your last device once you open the charging case after first connection, which is faster and more convenient. Touch control on the earbuds wireless bluetooth make it easy for you to manage listening modes or control volume. All operations at your fingertip, no need to adjust through your mobile phone. Compared with physical control, largely minimize the pressure to your ears. 5. Lightweight & IPX7 Sweatproof: Small and compact charging case, a single bud weighs only 3.5g holding it in hand as if it were nothing, which does not take up any space to carry. Featuring ergonomic semi-in-ear design, headphones wireless bluetooth provide a secure fit that snuggles nicely in your ears. The waterproof earbuds are equipped with nano-coated waterproof material, which can effectively prevent splash damage caused by sweat and raindrops, especially for sports and daily work.",
  'image': 'https://m.media-amazon.com/images/I/416BXxEsQRL._AC_.jpg',
  'rating_number': 145,
  'price': nan,
  'average_rating': 4.0,
  'parent_asin': 'B0C7434VVD'},
 {'preprocessed_description': 'BUFFBEE Digital Alarm Clock FM Radio - 10W Fast Wireless Charger Station & USB Port - 5 Wake Up Sounds, Volume Control, Full Brightness Dimmer for Bedroom All-In-One Design: It combines Alarm Clock, FM Radio, Wireless Charger and USB Charging Port - all in a minimalist fabric covered box, ultra-compact design fits easily on any table, bedroom and bedside for decor 10W Fast Wireless Charging: Supports 10W, 7.5W, and 5W adaptive charging pad - compatible with most universal enabled wireless charging devices, such as iPhone, Samsung Galaxy, Note, Google Nexus and other Android phones FM Radio with Superior Sound Quality: FM radio saves up to 30 stations, you can enjoy music and news through a high-performance driver and 5W stereo speaker, also supports saving your favorite radio station as the alarm sound to wake you up 0-100% Brightness Dimmable: Compared to other clocks of 3-level dimming, our digital alarm clock has more clear red numbers with full range of dimming - you can find the perfect brightness no matter day or night Wake Up with 5 Alarm Sounds: Choose from 5 alarm sounds (Beep, Birds, Bells, Piano music, Favorite radio) with 16 levels of adjustable volume - enjoy personalized alarm sound to wake you up in every peaceful morning',
  'image': 'https://m.media-amazon.com/images/I/51ZGvHzcmbL._AC_.jpg',

In [54]:
len(data_to_embed)

1000

In [55]:
text_to_embed=[item["preprocessed_description"] for item in data_to_embed]

In [56]:
text_to_embed

['3 Pack Fitbit Luxe Bands Compatible with Fitbit Luxe Women Men, Soft Silicone Wristband Replacement Strap for Fitbit Luxe/Luxe Special Edition Fitness Tracker Buckle closure 【Applicable Model】Meliya replacement wristbands Specially Designed for Fitbit Luxe / Fitbit Luxe Special Edition Only, NO Fitbit Luxe tracker included. 【Seamless Match】Fits as good as original Fitbit Luxe band. Simple to install and remove, NO tools required! The end of the band has a lug, which fit your Fitbit Luxe smart watch in place and locked precisely & securely. 【Premium Waterproof Material】Made from flexible high-quality elastomer, sweatproof & waterproof. Prevents skin from irritation, soft, lightweight and durable, very comfortable to wear. 【Available in Two Sizes】Small size: for 5.5"-7.3" wrists. Large size: for 6.7"-8.3" wrists 【After-sales Service】If you have any dissatisfaction with replacement bands for Fitbit Luxe from Meliya Store, please contact us via Amazon e-mail. We will reply to you ASAP.',
 'Charger Charging Cable Cord fits for Beats by Dr Dre Studio Solo 3 2, Powerbeats 3 2, Beats Studio Buds, Fit Pro, Flex Wireless Headphone Earbuds Earphone Adapter Power Supply (USB Type C & Micro) [Perfect compatibility]: Compatible with Beats Studio Buds, Beats Flex, Beats Fit Pro, Beats by dr dre Studio 2 3, Beats by dr dre Solo 2 3, Beats by dr dre Powerbeats 2 3, Beats Pill 2.0 Speakers. [Portable & Multifunctional]: The compact charger allows you to easily carry it and use it with a power bank. The two-in-one design of USB-C and USB-Micro brings you a wider range of usability. [Safety smart]: Built-in emergency protection mechanism with short circuit, over current, over voltage, over temperature protection. [Durable life]: The product has passed FCC/UL testing and certification, and the cable has undergone 10000+ bending violence tests. The charger has undergone rigorous drop and flame tests. [Lifetime friendly customer service]: If you are not satisfied with the product, please contact us!',
 'Wireless Keyboard and Mouse Combo, Giecy 2.4G Full-Sized Ergonomic Keyboard Mouse, Adjustable Ergonomic Full Size Keyboard USB Keyboard and Mouse, Plug & Play for Computer/Laptop/Windows/Mac 【Comfortable Wireless Keyboard Mouse Combo】 wireless keyboard mouse combo has a comfortable touch and typing feel, this wireless keyboard design with palm rest and folding holder that can protect your wrists from injury even when typing for a long time. NOTE: THE USB RECEIVER IS IN THE BATTERY COMPARTMENT OF THE MOUSE, YOU CAN FIND IT WHEN OPEN THE MOUSE BATTERY COVER. 【2.4G Stable Wireless Connection】This wireless keyboard and mouse combo share the same USB receiver, no need to take upadditional USB ports (Also the wireless keyboard and mouse can also be used separately). wireless keyboard and mouse Just plug USB receiver in device and turn keyboard on then enjoy no-lag play without any driver or pairing. 【Automatic Power Saving Function】The wireless keyboard and mouse combo has the function of automatically entering the power-saving state. When you stop using the keyboard for more than 15 minutes, stop using the mouse for more than 15 minutes, they will enter sleep mode respectively to save power. This feature greatly extends the battery life, you can click any button to activity the device. 【Adjustable Ergonomic Design computer keyboards】Our Full-Size Keyboard is designed with ergonomics in mind, allowing you to type comfortably for hours on end. 【Universal Compatibility】Our wireless computer keyboard is fully compatible with all major operating systems, including Windows, macOS, and Linux. promises that OUR PRODUCT HAVE A 12-MONTH FREE AFTER-SALES SERVICE. as long as you contact us, we will help you solve all problems.',
 "HoneyAKE Case for Google Pixel Buds A-Series Case 2021, Protective Cover for Google Pixel Buds A with Keychain Clip Security Lock Shockproof Google Pixel Buds A Earbuds Case Women Men Black Blue For Google Pixel Buds A-Series 2021 Case for Women Men: This charging case compatible with Google Pixel Buds A-Series 2021 wirless earphone. (NOTICE: Google Pixel Buds A device NOT included). HoneyAKE offers 12-month warranty for replacement or full refund without return the case. Metal Carabiner Design: This Google Pixel Buds A case cover with a carabiner. The carabiner can be hung on your belt, bag or key. And cover your new Google Pixel Buds A cover and fit well to provide secure 360° all-round protection. Security Lock Design: The Google Pixel Buds A-Series case can be fully opened up to 90°, very easy to take out and put in your compatible Google Pixel Buds A. And earphone shell is composed of upper and lower shells, adopts a split structure, and has a safety lock function on the front. Press the front locking button to automatically open the top cover. Support Wireless Charging: This Case fit for google pixel buds a-series case cover fully supports wireless charging without any interference and the LED indicator is visible. It is also convenient to charge the Pixel Buds A Charging cable without removing the case. Perfect Gift: This Cover for Google Pixel Buds A 2021 case for girls, women and men with Keychain ring holder is a great gift for your friends, girlfriend or familys on Birthday, Christmas, Thanksgiving, Halloween, Valentine's Day or other special days.",
 '2 Pack LCD Writing Tablet 12 Inch for Kids,Toys for 3 4 5 6 7 8 9 Year Old Girls Boys,LEYAOYAO Colorful Drawing Pad Doodle Board,Travel Learning Birthday Gift for 3 Age+ Toddler (Pink+Blue) Color drawing boards: We firmly believe that LEYAOYAO can make thousands of children write "I ♥ Mom" on the drawing board, then we will succeed. LCD writing tablet adopts the latest liquid crystal pressure-sensitive technology, which produces lines of different thicknesses according to the strength of your push. When boys and girls write, draw, and graffiti, different colors will appear on the drawing tablets. 2 pack sharing: 2 writing tablets 12Inch(1 Blue and 1 Pink). The electronic drawing tablet has one-key clear button, can be erased and written more than 100,000 times. magnetic learning toys for toddlers tablet.There is no mess of paper, crayons, markers or chalk at home.The key lock effectively prevents accidental clearing, and the screen can be erased when the writing pad unlocking. Multi-Purpose: our doodle board suitable for kids drawing,graffiti,painting,draft ,note taking,learning and scrawl at home ,school or travel etc.Toys for 3 4 5 6 7 8 9 years old girls boys. Lightweight and Portable: Made of high-quality plastic material, weighs only 280 grams, is easy to carry and travel in scheduler, briefcase or backpack, suitable for multiple occasions: living room, car,restaurant, plane,outdoor places. The writing tablet is waterproof and anti-fall, no need to worry about accidental dropping and liquid pouring on the screen. Best gifts: the best learning toy for kid. It can be an educational toy for preschoolers. It can be a travel toy for long drives and road trips. A parent-pick gift for kids 3+ age girl and boy on Valentine\'s day, back to school, homeschool,Easter,birthday,Children\'s Day,Thanksgiving Day, Christmas and any occasions!',
 "Video Conference Lighting for Laptop&Computer, Webcam Light for Streaming, Zoom Lighting for Computer, 3 Light Modes, 10 Brightness Adjustable, Metal Tripod for Self Broadcast,Live Streaming 【Newly Designed Multifunctional Video Conference Light】Show your best image in your online activities through this video conference light. It can significantly enhance your image in video conferences, online courses, live streaming, and other scenes through exquisite lighting, helping you showcase your confident and excellent side to others.At the same time, it also serves as a light source to provide corresponding lighting for reading, sleeping, resting, and makeup. 【Three Type Holder】Unique metal tripod made of frosted metal, which is more sturdy and stable than plastic. It is divided into two adjustable sections and easy to store;There are also two special clips：Adjustable clip has a greater up and down movement angle, making it more stable to use;The composite clip is more versatile, especially when the computer display screen is thicker, it can achieve better adaptation. You can choose the appropriate usage method according to your needs. 【3 Light Modes&10-Level Brightness】There are three lighting modes available: natural light (suitable for work, video conferencing), white light (high brightness, suitable for dim environments), and warm light (suitable for bedroom, restaurant). The color temperature of 2500-9000K is much higher than the market average of 6500K, providing higher brightness and more options.10-Level brightness adjustments means you can choose the appropriate brightness based on your needs using the remote control. 【Asymmetric Light Source Design&USB-powered&Space-saving】The 45° asymmetric light source design reduces reflections from computer screens, protecting your eyes and vision. The light is powered via a USB Type-C interface, eliminating concerns about battery depletion during use. With its slim and compact dimensions of 11.02 * 1.6 * 0.3in, it doesn't take up any desktop space, enhancing work efficiency. 【Packaging Content & After-Sales Guarantee】Package content: video conference light * 1,Metal tripod * 1, anti-skid clip * 1, USB remote controller * 1, instruction manual * 1.Our shop guarantees a one-year warranty. If you have any quality problems, please contact us, and we will help you solve them.",
 'LFS Portable Bluetooth Shower Speaker, Waterproof Outdoor Wireless Speaker, Ultra-Long Play Time 15 Hours, TWS Pairing, Suitable for Home, Pool, Beach, Boating, Hiking, Camping TWS Dual Stereo: updated sound with 10W high stereo power through two Bluetooth speakers connected together! speakers bluetooth wireless has crystal clear sound and rich, full bass, you will be blown away by the HD quality sound Bluetooth version 5.0: Portable wireless Bluetooth speaker uses advanced Bluetooth technology to provide fast connectivity as well as greater wireless range and more stable Bluetooth connection for all Bluetooth devices. Such as cell phones, tablets, laptops, computers, Macbooks, MP3 players, etc Super long playing time: LFS portable Bluetooth speaker has a built-in 1500mAh rechargeable lithium battery, Bluetooth speaker can be used up to 15 hours, so you can enjoy music from morning to night, never stop Waterproof and Dustproof: Bluetooth waterproof outdoor speaker ensures dustproof, waterproof, shockproof, rainproof and snowproof, perfect for hiking, rafting, boating, swimming, kayaking and showering, etc. Bring our Bluetooth speaker and let it be your good companion also let you be a travel rocker Lightweight and portable small size: portable wireless bluetooth speaker wears a lanyard and has a built-in microphone that makes it easy to take calls via bluetooth mode. bluetooth speakers modern design makes it a great gift choice for any occasion, at a friends party, going camping outdoors with family and friends, etc',
 'DTTOCASE iPad 10th Generation Kickstand Protective Case 2022,iPad 10.9 Inch Cover with Matte Frosted Shockproof Back [Anti-Fingerprint,Anti-Scratch,Support Touch ID,Camera Protection]-Rose Gold ⭐【Compatibility Model】This Matte Frosted Case is compatible with Apple iPad 10th Generation 10.9 inch Model Number:A2757/A2777/A2696 (2022 released)(2022 released), Not compatible with any other iPad devices. ⭐【Three-in-One Cover】Offers the difference by Ultra Hybrid protection Design, Hard Matte Frosted PC back provides strong support, Anti-Fingerprint and Anti-Scratch.and Soft TPU frame protects your iPad from shocks, drops, and impacts. Front Screen Protector cover prevents scratches without compromising sensitivity. ⭐【 Slim and Stylish 】Precise cutouts for all buttons and ports with just 0.6-inches Thickness, Minimalist shape,Matte frosted translucent back, and beautiful colors bring you to ease and comfort at any time. ⭐【Multiple Function】This iPad case has Pencil Holder to support Touch ID, Camera Protection, Two Kickstand Angle - gives you 2 different comfortable angles. ⭐【Lifetime Warranty 】DTTOCASE Offers Lifetime Free Replacement for Your IPad Case. (Needs to be activated within 30 days of purchasing) Your Satisfaction Is Our Top Concern.',
 '2Pack Security Cameras Outdoor Wireless, 2K Surveillance Camera with Night Vision, Motion Detection, IP66 Waterproof, Cloud Storage, 24/7 Recordings, Live View, Work with Alexa Google Assitant 24/7 continuous recordings & IP66 waterproof - Watching home security, day and night, with 24/7 live video.Rraycom Indoor Cam plugs into power, never have to worry about dead batteries. Security camera with IP66 ultra-high waterproof performance can connect to 2.4 Ghz wifi, support installation anywhere (need plug in) 2K QHD clear resolution & Night vision - With 3MP ultra-high definition, you can see clearer details than 1080P cameras. A stunning night vision security camera allows you to get a clear picture even in total darkness. Smart AI recognition & Custom delineated area - Wireless cameras for home security with advanced smart AI detection can easily distinguish humans, vehicle or animal, you can also manually define detection areas to improve alert accuracy and reduce unnecessary reminders. Work with Alexa and Google Assistant - The Rraycom wireless outdoor camera support voice control via Alexa/Google Assistant-enabled device. Hands-free with Alexa by saying, "Alexa, show me the living room" to view a live stream via the echo show.---Note: The outdoor camera does not support a two-way audio function. 30-days Free Trial of Cloud Service - Enjoy a 30-days free trial of the “meshare” 7-days cloud recording plan. With the plan, you can review, save, and share footage at any time. You can subscribe to the Premium plan Or Platinum plan of the cloud service after the cloud service trial expired.',
 "Bluetooth Headphones Wireless Earbuds 50Hrs Playtime with Wireless Charging Case Dual LED Display Ear Buds Waterproof Immersive Stereo in-Ear Earphones with Mic for Phone TV Computer Android White 1. Dual LED Power Display: Bluetooth headphones with dual battery display show the remaining juice of charging case by the number on the screen, and the charging status of ear buds by up and down of LED bar. When the wireless earbuds are charging, the LED bars flash from 1st to 4th grid repeatedly, and go out after fully charged. Also you can easily know the battery consumption on both wireless headphones and the charging case so you can master the best time to charge it. 2. Up to 50Hrs Playtime with Wireless Charging Case: Each bluetooth earbud lasts around 5 hours on a single charge for normal use (100% volume), more than 50 hours total listening time with the portable charging case, which can be charged via the included USB-C cable or wirelessly with any QI-certified charging mat (not included). These wireless headphones bluetooth have enough battery to last all day and all night. Keep your own private concert going for as long as you can keep up. 3. Hi-Fi Stereo Sound & Crystal Clear Call: Supported by a powerful 12mm speaker driver unit and semi-in-ear acoustic structure to produce sound with strong bass, clear mids, and bright treble. Unique chamber acoustic design balances the internal and external air pressure to avoid sound loss, making sure the sound stable and penetrating to provide clear voice detection even in noisy environments. Enjoy your personal space whether you're indoors, outdoors, work or sports. 4. One-step Pairing & Smart Touch Control: Built in hall switch, bluetooth earphones will auto power on and connect with your last device once you open the charging case after first connection, which is faster and more convenient. Touch control on the earbuds wireless bluetooth make it easy for you to manage listening modes or control volume. All operations at your fingertip, no need to adjust through your mobile phone. Compared with physical control, largely minimize the pressure to your ears. 5. Lightweight & IPX7 Sweatproof: Small and compact charging case, a single bud weighs only 3.5g holding it in hand as if it were nothing, which does not take up any space to carry. Featuring ergonomic semi-in-ear design, headphones wireless bluetooth provide a secure fit that snuggles nicely in your ears. The waterproof earbuds are equipped with nano-coated waterproof material, which can effectively prevent splash damage caused by sweat and raindrops, especially for sports and daily work.",
 'BUFFBEE Digital Alarm Clock FM Radio - 10W Fast Wireless Charger Station & USB Port - 5 Wake Up Sounds, Volume Control, Full Brightness Dimmer for Bedroom All-In-One Design: It combines Alarm Clock, FM Radio, Wireless Charger and USB Charging Port - all in a minimalist fabric covered box, ultra-compact design fits easily on any table, bedroom and bedside for decor 10W Fast Wireless Charging: Supports 10W, 7.5W, and 5W adaptive charging pad - compatible with most universal enabled wireless charging devices, such as iPhone, Samsung Galaxy, Note, Google Nexus and other Android phones FM Radio with Superior Sound Quality: FM radio saves up to 30 stations, you can enjoy music and news through a high-performance driver and 5W stereo speaker, also supports saving your favorite radio station as the alarm sound to wake you up 0-100% Brightness Dimmable: Compared to other clocks of 3-level dimming, our digital alarm clock has more clear red numbers with full range of dimming - you can find the perfect brightness no matter day or night Wake Up with 5 Alarm Sounds: Choose from 5 alarm sounds (Beep, Birds, Bells, Piano music, Favorite radio) with 16 levels of adjustable volume - enjoy personalized alarm sound to wake you up in every peaceful morning',
 'Bluetooth Home Stereo Shelf System - Compact Micro Stereo System with CD Player, FM Radio, Aux-in, USB Playback, 2-Way Music Crisp-Sound, DSP-Tech, Remote Control ► Compact Stereo system --- The LP-886 micro hi-fi system offers pure listening pleasure thanks to high-quality stereo speakers. This all-in-one hi-fi audio system is a complete solution for your hearing needs. Sit back and enjoy all that it has to offer. ► Rich & Clear Sounds --- Stereo systems Bulti-in DSP technology, provide 30W (2 x 15W RMS)/40 W Max via the power of 2-way speakers: ① High-performance silk dome tweeters for smooth treble and precise imaging; ② Balanced Rubber Woofer for powerful and transient bass. ► Multi-mode Micro Shelf System --- This small stereo system is a complete solution that meets more requirements: ① Top-loading CD player supports CD/CD-R/CD-RW; ② Packed with features for listening to FM radio (NOT AM); ③ Wireless streaming of audio content from your smartphone/mobile phone via Bluetooth, ④Play MP3s/WMAs via USB, ⑤ 3.5mm aux input for playing audio from other devices. ► Unique design and Functional - - Two Wooden Speakers with rounded corners; Main mechine with big Knob, and white backlit LED display Screen; headphone jack for private listening; come with confortable remote control for convenient use. It also has memory function, 5 EQ modes and 3 repeat modes (one /all /random ) ► Ideal gift --- The best birthday, Christmas, festival gift for lovers, children, parents, friends, family members, colleagues! You get: 1 x CD Micro System Player, 1 x Remote Control, 1 x User Manual. 12-month replacement warranty and 24-hour customer service (supplied by the seller). * Kindly Note: 1.OPEN/CLOSE CD lid need press in right position.2. The display of the main unit has a transparent protective film that you can tear off if you do not like it. Please contact the seller if you encounter a problem. Thank you!',

In [57]:
embeddings=get_embeddings_batch(text_to_embed)

Processed 100 of 1000
Processed 200 of 1000
Processed 300 of 1000
Processed 400 of 1000
Processed 500 of 1000
Processed 600 of 1000
Processed 700 of 1000
Processed 800 of 1000
Processed 900 of 1000
Processed 1000 of 1000

In [58]:
pointstructs = []
i=1
for embedding, data in zip(embeddings, data_to_embed):
    pointstructs.append(
        PointStruct(
            id=i,
            vector={
                "text-embedding-3-small": embedding,
                "bm25": Document(
                    text=data["preprocessed_description"],
                    model="qdrant/bm25"
                )
            },
            payload=data
        )
    )
    i += 1

In [26]:
pointstructs[0].vector

{'text-embedding-3-small': [0.01142120361328125,
  0.00748443603515625,
  -0.007244110107421875,
  -0.035888671875,
  -0.031890869140625,
  -0.042999267578125,
  -0.0450439453125,
  0.0243072509765625,
  0.0271453857421875,
  -0.06817626953125,
  -0.0036487579345703125,
  -0.0159149169921875,
  -0.0297393798828125,
  -0.026947021484375,
  0.032318115234375,
  0.039337158203125,
  -0.036529541015625,
  -0.005077362060546875,
  -0.051666259765625,
  0.05487060546875,
  0.001708984375,
  0.045379638671875,
  0.003276824951171875,
  -0.049774169921875,
  0.0026340484619140625,
  -0.019805908203125,
  -0.04425048828125,
  -0.00902557373046875,
  -0.005672454833984375,
  0.059722900390625,
  0.017669677734375,
  -0.01080322265625,
  0.01038360595703125,
  -0.0325927734375,
  -0.02703857421875,
  0.033172607421875,
  0.01947021484375,
  -0.01230621337890625,
  0.03875732421875,
  0.0214691162109375,
  -0.006061553955078125,
  0.050445556640625,
  0.00634002685546875,
  0.00482940673828125,
  0.009796142578125,
  0.0016460418701171875,
  -0.016571044921875,
  0.04595947265625,
  -0.05010986328125,
  0.031585693359375,
  0.0162506103515625,
  0.020172119140625,
  -0.007015228271484375,
  0.01285552978515625,
  0.02301025390625,
  -0.031341552734375,
  -0.01019287109375,
  0.041717529296875,
  -0.0033321380615234375,
  0.0131683349609375,
  -0.0577392578125,
  0.0009250640869140625,
  0.0015230178833007812,
  -0.015411376953125,
  -0.033203125,
  -0.0016422271728515625,
  -0.01214599609375,
  0.00629425048828125,
  -0.00656890869140625,
  -0.04449462890625,
  -0.0090179443359375,
  -0.0301055908203125,
  0.00298309326171875,
  0.0355224609375,
  0.007389068603515625,
  -0.00726318359375,
  0.0243682861328125,
  0.0161590576171875,
  0.01416778564453125,
  0.03570556640625,
  0.0006403923034667969,
  -0.01300048828125,
  -0.05126953125,
  0.0418701171875,
  -0.048065185546875,
  0.051116943359375,
  -0.04339599609375,
  -0.0179290771484375,
  -0.00879669189453125,
  -0.0092620849609375,
  0.032562255859375,
  -0.07080078125,
  -0.0264434814453125,
  0.0148773193359375,
  -0.04296875,
  0.042083740234375,
  -0.03802490234375,
  0.0081939697265625,
  -0.0489501953125,
  0.05352783203125,
  0.0113983154296875,
  0.00833892822265625,
  0.00899505615234375,
  -0.0142822265625,
  -0.01316070556640625,
  0.00225830078125,
  0.029052734375,
  0.0072784423828125,
  0.03228759765625,
  -0.0218505859375,
  0.0224151611328125,
  0.01690673828125,
  0.01070404052734375,
  0.0199737548828125,
  0.04779052734375,
  0.034210205078125,
  0.036895751953125,
  -0.01155853271484375,
  0.01111602783203125,
  -0.04071044921875,
  0.0243072509765625,
  0.06927490234375,
  0.026397705078125,
  -0.0322265625,
  -0.0235137939453125,
  0.01560211181640625,
  -0.0043487548828125,
  -0.02703857421875,
  -0.0258941650390625,
  -0.044464111328125,
  0.025726318359375,
  -0.0146026611328125,
  0.0169830322265625,
  0.01369476318359375,
  0.018890380859375,
  -0.0248565673828125,
  -0.02264404296875,
  -0.007007598876953125,
  -0.059173583984375,
  -0.012542724609375,
  0.0179290771484375,
  -0.00927734375,
  0.027557373046875,
  -0.0039005279541015625,
  0.00713348388671875,
  -0.0171661376953125,
  0.0582275390625,
  -0.04449462890625,
  -0.04144287109375,
  0.006061553955078125,
  -0.0179901123046875,
  -0.00748443603515625,
  0.03570556640625,
  0.01004791259765625,
  0.026275634765625,
  -0.06500244140625,
  0.032318115234375,
  -0.00302886962890625,
  -0.0012874603271484375,
  0.01549530029296875,
  0.044830322265625,
  0.02093505859375,
  0.0287017822265625,
  -0.0175018310546875,
  0.0263214111328125,
  0.0151519775390625,
  0.023956298828125,
  -0.041168212890625,
  -0.0418701171875,
  -0.0143280029296875,
  0.034423828125,
  0.0168609619140625,
  0.0093231201171875,
  -0.0101318359375,
  0.0139923095703125,
  -0.045196533203125,
  -0.0232086181640625,
  -0.0161285400390625,
  -0.005126953125,
  0.0159759521484375,
  0.00402069091796875,
  0.006427764892578125,
  0.003276824951171875,
  0.058074951171875,
  -0.05035400390625,
  0.0186920166015625,
  -0.028106689453125,
  -0.00547027587890625,
  0.00905609130859375,
  -0.0020236968994140625,
  -0.005344390869140625,
  0.01263427734375,
  -0.0162506103515625,
  -0.01549530029296875,
  -0.048614501953125,
  -0.0194091796875,
  0.043609619140625,
  0.00908660888671875,
  0.016754150390625,
  0.015899658203125,
  0.018890380859375,
  -0.008026123046875,
  0.05181884765625,
  0.007717132568359375,
  0.002109527587890625,
  0.01174163818359375,
  -0.08135986328125,
  0.0245513916015625,
  0.01165771484375,
  -0.0215911865234375,
  0.033660888671875,
  0.03662109375,
  0.02716064453125,
  -0.052978515625,
  0.006145477294921875,
  0.00951385498046875,
  0.025299072265625,
  -0.058868408203125,
  0.018951416015625,
  0.05230712890625,
  -0.02001953125,
  0.029937744140625,
  0.049102783203125,
  0.0194091796875,
  -0.048492431640625,
  -0.0176849365234375,
  0.059051513671875,
  -0.041839599609375,
  -0.054473876953125,
  0.00875091552734375,
  -0.0243377685546875,
  0.0040740966796875,
  -0.01983642578125,
  -0.000507354736328125,
  0.02783203125,
  -0.046051025390625,
  -0.04351806640625,
  -0.01303863525390625,
  0.0134124755859375,
  -0.048492431640625,
  -0.0361328125,
  0.0030231475830078125,
  -0.04473876953125,
  0.0275421142578125,
  0.00894927978515625,
  -0.0298614501953125,
  -0.01145172119140625,
  -0.038848876953125,
  0.007678985595703125,
  0.007106781005859375,
  0.0168304443359375,
  -0.01186370849609375,
  0.02447509765625,
  -0.003971099853515625,
  0.037628173828125,
  0.07818603515625,
  0.010955810546875,
  0.040374755859375,
  -0.032958984375,
  -0.0186767578125,
  -0.01519012451171875,
  0.01032257080078125,
  -0.046844482421875,
  -0.0009937286376953125,
  0.012451171875,
  -0.0302734375,
  -0.032867431640625,
  0.033416748046875,
  0.0167694091796875,
  0.0250244140625,
  -0.002155303955078125,
  -0.011077880859375,
  -0.044036865234375,
  -0.0091705322265625,
  0.023956298828125,
  0.00582122802734375,
  0.0175018310546875,
  -0.0294647216796875,
  0.00437164306640625,
  0.038665771484375,
  0.034332275390625,
  -0.04425048828125,
  -0.026214599609375,
  -0.038238525390625,
  -0.0018796920776367188,
  -0.01264190673828125,
  0.03662109375,
  -0.0277862548828125,
  -0.0335693359375,
  0.0219573974609375,
  -0.0154266357421875,
  -0.017242431640625,
  -0.0297088623046875,
  -0.04559326171875,
  -0.032318115234375,
  0.0033130645751953125,
  0.019805908203125,
  -0.0159454345703125,
  -0.0460205078125,
  -0.01517486572265625,
  -0.0201263427734375,
  0.051116943359375,
  -0.0215606689453125,
  0.0207977294921875,
  -0.0007419586181640625,
  0.0192413330078125,
  0.024200439453125,
  -0.04022216796875,
  -0.034759521484375,
  0.01015472412109375,
  0.020111083984375,
  0.01043701171875,
  0.00665283203125,
  -0.023193359375,
  0.00803375244140625,
  -0.05133056640625,
  -0.004184722900390625,
  -0.0003726482391357422,
  -0.0100250244140625,
  -0.03338623046875,
  0.05804443359375,
  -0.0017108917236328125,
  -0.01264190673828125,
  -0.031585693359375,
  0.0006475448608398438,
  -0.015594482421875,
  -0.024169921875,
  -0.04254150390625,
  -0.030426025390625,
  -0.0621337890625,
  0.019195556640625,
  -0.023895263671875,
  -0.035675048828125,
  -0.05224609375,
  -0.0377197265625,
  -0.007232666015625,
  0.0362548828125,
  -0.005786895751953125,
  0.011322021484375,
  0.08551025390625,
  0.021759033203125,
  -0.050567626953125,
  -0.004009246826171875,
  7.480382919311523e-05,
  0.001422882080078125,
  -0.026214599609375,
  0.040496826171875,
  -0.0188446044921875,
  -0.0012674331665039062,
  -0.0024929046630859375,
  -0.022186279296875,
  -0.0159912109375,
  0.029876708984375,
  -0.06951904296875,
  0.007396697998046875,
  -0.0297393798828125,
  0.0631103515625,
  -0.060546875,
  0.01837158203125,
  0.00432586669921875,
  0.01203155517578125,
  0.029876708984375,
  -0.032196044921875,
  -0.0048828125,
  -0.020751953125,
  0.04205322265625,
  0.01441192626953125,
  -0.007343292236328125,
  2.0742416381835938e-05,
  0.0224761962890625,
  0.0435791015625,
  0.0125274658203125,
  0.0178070068359375,
  0.0051727294921875,
  -0.040618896484375,
  0.03680419921875,
  0.00441741943359375,
  0.06982421875,
  -0.050994873046875,
  -0.046844482421875,
  0.01021575927734375,
  -0.018310546875,
  0.025726318359375,
  -0.005344390869140625,
  -0.0011844635009765625,
  0.03228759765625,
  -0.0460205078125,
  0.00589752197265625,
  0.0287017822265625,
  -0.0235137939453125,
  0.0069122314453125,
  0.047271728515625,
  0.05841064453125,
  -0.04071044921875,
  0.051971435546875,
  0.0216522216796875,
  0.09967041015625,
  0.00684356689453125,
  -0.00841522216796875,
  -0.04266357421875,
  0.02392578125,
  -0.027008056640625,
  -0.0214996337890625,
  0.0029315948486328125,
  -0.049041748046875,
  0.012359619140625,
  0.0191497802734375,
  0.0286102294921875,
  -0.00872039794921875,
  0.017852783203125,
  -0.01471710205078125,
  -0.02294921875,
  0.0037841796875,
  -0.01303863525390625,
  0.03375244140625,
  0.0256195068359375,
  0.03961181640625,
  0.00913238525390625,
  0.03546142578125,
  -0.003223419189453125,
  -0.03594970703125,
  -0.048370361328125,
  0.016387939453125,
  -0.0096282958984375,
  -0.025115966796875,
  0.005275726318359375,
  0.031829833984375,
  -0.06451416015625,
  -0.00466156005859375,
  -0.0307159423828125,
  -0.042327880859375,
  0.0101470947265625,
  0.02545166015625,
  -0.028106689453125,
  -0.0270538330078125,
  -0.04425048828125,
  0.024993896484375,
  0.0125579833984375,
  -0.0078887939453125,
  0.0168304443359375,
  0.005268096923828125,
  -0.039825439453125,
  0.02490234375,
  0.0294189453125,
  0.037139892578125,
  0.0268707275390625,
  -0.03900146484375,
  0.04052734375,
  -0.0166473388671875,
  -0.006954193115234375,
  -0.0623779296875,
  0.0330810546875,
  0.00029397010803222656,
  -0.01338958740234375,
  0.02008056640625,
  0.01512908935546875,
  -0.03668212890625,
  -0.038848876953125,
  0.032073974609375,
  -0.00018835067749023438,
  0.03204345703125,
  0.01605224609375,
  0.0621337890625,
  -0.0113525390625,
  -0.0289459228515625,
  0.01363372802734375,
  -0.0039215087890625,
  0.0189971923828125,
  0.027984619140625,
  -0.0304412841796875,
  0.0035266876220703125,
  -0.03741455078125,
  0.00251007080078125,
  0.058929443359375,
  -0.01007843017578125,
  -0.00984954833984375,
  0.021697998046875,
  -0.00516510009765625,
  -0.0209808349609375,
  0.0238494873046875,
  -0.01503753662109375,
  0.004673004150390625,
  -0.07318115234375,
  1.1265277862548828e-05,
  -0.01451873779296875,
  0.04638671875,
  0.047821044921875,
  -0.005924224853515625,
  -0.060516357421875,
  -0.0033969879150390625,
  -0.0124969482421875,
  -0.02490234375,
  -0.05853271484375,
  -0.00634765625,
  0.0665283203125,
  -0.02886962890625,
  0.0100860595703125,
  -0.034423828125,
  -0.006969451904296875,
  -0.002658843994140625,
  0.0235595703125,
  -0.02325439453125,
  0.007678985595703125,
  0.026824951171875,
  -0.016326904296875,
  0.0218658447265625,
  0.00901031494140625,
  -0.0226898193359375,
  -0.003452301025390625,
  0.0302581787109375,
  -0.0016489028930664062,
  0.0007457733154296875,
  0.001384735107421875,
  -0.005035400390625,
  -0.02435302734375,
  0.020416259765625,
  0.019439697265625,
  0.0246429443359375,
  -0.01824951171875,
  -0.0107269287109375,
  -0.0274505615234375,
  0.03839111328125,
  0.0198211669921875,
  -0.0271453857421875,
  -0.0250091552734375,
  0.0088653564453125,
  -0.0158843994140625,
  -0.056121826171875,
  -0.035064697265625,
  -0.01329803466796875,
  -0.01995849609375,
  0.0015316009521484375,
  -0.014739990234375,
  0.0280303955078125,
  0.0304107666015625,
  0.01611328125,
  -0.01297760009765625,
  -0.01244354248046875,
  0.0002892017364501953,
  0.0258026123046875,
  -0.0216522216796875,
  0.00730133056640625,
  -0.007076263427734375,
  0.016693115234375,
  0.0144195556640625,
  -0.01117706298828125,
  -0.052886962890625,
  -0.01169586181640625,
  0.0234832763671875,
  -0.01297760009765625,
  0.023529052734375,
  -0.01055145263671875,
  0.032379150390625,
  0.026123046875,
  -0.0183868408203125,
  0.0614013671875,
  0.005939483642578125,
  0.0175323486328125,
  0.0521240234375,
  0.017852783203125,
  0.02215576171875,
  0.006927490234375,
  0.0199432373046875,
  0.0286712646484375,
  0.004329681396484375,
  -0.0026378631591796875,
  0.0116729736328125,
  0.0224761962890625,
  -0.007076263427734375,
  -0.0032367706298828125,
  -0.049468994140625,
  -0.0243682861328125,
  -0.0269927978515625,
  -0.027923583984375,
  0.023895263671875,
  -0.007274627685546875,
  -0.0299072265625,
  0.01151275634765625,
  -0.01413726806640625,
  0.02130126953125,
  -0.01422119140625,
  -0.0322265625,
  0.03680419921875,
  0.0015573501586914062,
  -0.07171630859375,
  0.0236358642578125,
  -0.0462646484375,
  -0.0391845703125,
  0.0018873214721679688,
  0.040252685546875,
  -0.0184326171875,
  -0.0308074951171875,
  -0.0243072509765625,
  0.038360595703125,
  0.0256195068359375,
  -0.01459503173828125,
  -0.0245208740234375,
  -0.0035381317138671875,
  0.00785064697265625,
  -0.00588226318359375,
  -0.0008397102355957031,
  -0.0222930908203125,
  0.0171051025390625,
  -0.00027632713317871094,
  -0.0013170242309570312,
  0.04486083984375,
  0.0665283203125,
  -0.0184783935546875,
  -0.03167724609375,
  0.0352783203125,
  -0.011383056640625,
  -0.0164947509765625,
  0.045074462890625,
  -0.004108428955078125,
  -0.026824951171875,
  -0.0229034423828125,
  -0.02154541015625,
  -0.025665283203125,
  0.04132080078125,
  0.002399444580078125,
  0.0176239013671875,
  0.0289306640625,
  0.03704833984375,
  0.0191497802734375,
  0.02850341796875,
  0.012939453125,
  0.01374053955078125,
  -0.058990478515625,
  -0.0185394287109375,
  0.0092926025390625,
  0.0038928985595703125,
  0.00682830810546875,
  0.02557373046875,
  0.01358795166015625,
  -0.004764556884765625,
  0.0159912109375,
  0.00046563148498535156,
  0.04205322265625,
  -0.029205322265625,
  0.019775390625,
  0.0188140869140625,
  -0.03436279296875,
  0.0298004150390625,
  -0.0164337158203125,
  -0.030792236328125,
  -0.006526947021484375,
  0.025787353515625,
  0.022125244140625,
  -0.00730133056640625,
  0.013275146484375,
  0.0224609375,
  -0.032501220703125,
  -0.022308349609375,
  0.03668212890625,
  0.016998291015625,
  0.0261077880859375,
  -0.003589630126953125,
  0.01355743408203125,
  0.03955078125,
  -0.06787109375,
  -0.0054779052734375,
  0.048065185546875,
  0.0167083740234375,
  -0.03564453125,
  -0.0260467529296875,
  0.056060791015625,
  0.0028553009033203125,
  0.007381439208984375,
  0.030242919921875,
  0.00702667236328125,
  0.038482666015625,
  0.01517486572265625,
  -0.00044918060302734375,
  -0.003631591796875,
  -0.00827789306640625,
  0.00823211669921875,
  0.0323486328125,
  -0.0211944580078125,
  -0.0087127685546875,
  -0.00226593017578125,
  -0.006542205810546875,
  -0.01522064208984375,
  -0.01476287841796875,
  0.01271820068359375,
  0.0269012451171875,
  -0.01678466796875,
  0.0093231201171875,
  0.02825927734375,
  -0.033203125,
  -0.034637451171875,
  -0.023590087890625,
  0.007022857666015625,
  -0.0026187896728515625,
  -0.0024261474609375,
  0.016143798828125,
  -0.0347900390625,
  0.01422119140625,
  0.0275115966796875,
  -0.018035888671875,
  0.00400543212890625,
  0.003284454345703125,
  0.01715087890625,
  -0.034698486328125,
  -0.000873565673828125,
  -0.0259857177734375,
  0.0196380615234375,
  -0.0196685791015625,
  -0.0144195556640625,
  0.048065185546875,
  0.00870513916015625,
  -0.0225677490234375,
  0.01519012451171875,
  0.00997161865234375,
  -0.03515625,
  -0.0001659393310546875,
  -0.033660888671875,
  0.033203125,
  0.0421142578125,
  -0.011016845703125,
  0.032867431640625,
  -0.01044464111328125,
  0.01312255859375,
  -0.0305328369140625,
  0.01036834716796875,
  0.0182037353515625,
  0.027618408203125,
  0.00823974609375,
  0.045257568359375,
  0.0084228515625,
  -0.0386962890625,
  -0.030914306640625,
  0.0199432373046875,
  0.034423828125,
  -0.00311279296875,
  -0.01229095458984375,
  -0.01232147216796875,
  0.024505615234375,
  -0.01476287841796875,
  -0.0167999267578125,
  -0.00696563720703125,
  0.007152557373046875,
  0.04669189453125,
  -0.0270538330078125,
  -0.0128631591796875,
  0.03839111328125,
  0.0452880859375,
  0.0099029541015625,
  0.0031833648681640625,
  -0.0128936767578125,
  0.0015287399291992188,
  0.01617431640625,
  0.004497528076171875,
  0.0143890380859375,
  0.01158905029296875,
  -0.0187530517578125,
  -0.044830322265625,
  -0.00894927978515625,
  -0.01230621337890625,
  0.0028095245361328125,
  -0.0169219970703125,
  0.00585174560546875,
  0.027435302734375,
  0.0204925537109375,
  -0.004016876220703125,
  -0.010345458984375,
  0.0087890625,
  -0.07611083984375,
  0.0260467529296875,
  -0.0175628662109375,
  -0.020721435546875,
  -0.0224609375,
  0.0003643035888671875,
  0.06915283203125,
  0.006099700927734375,
  0.008331298828125,
  -0.048004150390625,
  -0.013916015625,
  0.00809478759765625,
  -0.019866943359375,
  0.007587432861328125,
  0.0108489990234375,
  0.0372314453125,
  0.0005750656127929688,
  0.00759124755859375,
  -0.007091522216796875,
  0.0174713134765625,
  0.00965118408203125,
  -0.0042877197265625,
  -0.008636474609375,
  0.01079559326171875,
  0.0074005126953125,
  -0.0104217529296875,
  -0.01605224609375,
  -0.05059814453125,
  0.02545166015625,
  0.0011577606201171875,
  -0.0013532638549804688,
  -0.005645751953125,
  -0.01531219482421875,
  0.025177001953125,
  -0.0176239013671875,
  -0.0165252685546875,
  -0.01183319091796875,
  0.005489349365234375,
  0.0226898193359375,
  -0.007427215576171875,
  -0.036590576171875,
  0.0701904296875,
  0.0100555419921875,
  0.0131988525390625,
  -0.007656097412109375,
  0.00034236907958984375,
  0.031036376953125,
  0.004199981689453125,
  0.026123046875,
  0.0115966796875,
  0.030975341796875,
  0.0253448486328125,
  0.0085906982421875,
  0.0007638931274414062,
  0.045501708984375,
  0.006145477294921875,
  -0.0238494873046875,
  -0.0009598731994628906,
  0.004276275634765625,
  -0.00034689903259277344,
  0.0134735107421875,
  0.017547607421875,
  0.026458740234375,
  -0.036529541015625,
  -0.027099609375,
  0.0137786865234375,
  0.0288238525390625,
  -0.00266265869140625,
  0.008148193359375,
  0.0271759033203125,
  -0.026153564453125,
  0.030181884765625,
  0.02490234375,
  0.014404296875,
  0.0017938613891601562,
  -0.04315185546875,
  0.00403594970703125,
  0.00345611572265625,
  -0.0099029541015625,
  -0.0168304443359375,
  -0.003086090087890625,
  0.0030307769775390625,
  0.018402099609375,
  0.004413604736328125,
  0.0004911422729492188,
  0.023590087890625,
  0.029205322265625,
  0.006130218505859375,
  0.00420379638671875,
  0.00868988037109375,
  0.024505615234375,
  -0.033203125,
  0.004810333251953125,
  0.003200531005859375,
  -0.036163330078125,
  -0.004711151123046875,
  -0.0084686279296875,
  0.000736236572265625,
  0.002132415771484375,
  0.0013179779052734375,
  -0.01383209228515625,
  0.013641357421875,
  -0.021697998046875,
  -0.00913238525390625,
  0.0252685546875,
  0.031951904296875,
  -0.027099609375,
  -0.04150390625,
  0.005496978759765625,
  0.0066070556640625,
  0.030029296875,
  0.05621337890625,
  0.0222930908203125,
  0.005962371826171875,
  0.01192474365234375,
  0.02557373046875,
  -0.004669189453125,
  0.018707275390625,
  -0.003414154052734375,
  0.0222930908203125,
  -0.00482177734375,
  0.055572509765625,
  0.05023193359375,
  -0.037384033203125,
  -0.017486572265625,
  -0.0002694129943847656,
  -0.032257080078125,
  0.017852783203125,
  -0.017120361328125,
  -0.004253387451171875,
  0.0200958251953125,
  0.020843505859375,
  -0.006317138671875,
  -0.019989013671875,
  0.01319122314453125,
  -0.0244140625,
  -0.01433563232421875,
  0.01763916015625,
  -0.0003814697265625,
  0.0030517578125,
  0.007244110107421875,
  0.021820068359375,

In [59]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-01-hybrid-search",
    points=pointstructs[0:500],
    wait=True
)

UpdateResult(operation_id=3, status=<UpdateStatus.COMPLETED: 'completed'>)

In [60]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-01-hybrid-search",
    points=pointstructs[500:],
    wait=True
)

UpdateResult(operation_id=4, status=<UpdateStatus.COMPLETED: 'completed'>)

Hybrid Retrieval

In [61]:
def retrieve_data(query, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-hybrid-search",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                limit=20
            ),
            Prefetch(
                query=Document(
                    text=query,
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    retrieved_context_ratings = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_description"])
        similarity_scores.append(result.score)
        retrieved_context_ratings.append(result.payload["average_rating"])

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
        "retrieved_context_ratings": retrieved_context_ratings
    }

In [62]:
results = retrieve_data("Can I get a tablet?", k=20)

In [63]:
results

{'retrieved_context_ids': ['B0BN7JTB5N',
  'B0B7QL4FMN',
  'B0C4KCQB19',
  'B09MKYBJT6',
  'B0BJPTYFK9',
  'B07FMF2L6B',
  'B0BCFYCXRH',
  'B0B3QGL9C9',
  'B0BDD6BC6Y',
  'B0BQ1ZVF2C',
  'B0C6QXGW5S',
  'B0BCDYMF5L',
  'B0C1TWNBGD',
  'B0BHP1HMK2',
  'B09MFHFHQM',
  'B0B9JSJ2RF',
  'B0BKZN3N6L',
  'B0B1DFWMLK',
  'B0BGLJC82D',
  'B0B7MR7WS7'],
 'retrieved_context': ['UGREEN 2 Pack Tablet Stand Holder Adjustable Desktop Portable Stand Home Office Desk Accessories Compatible with iPad 10.2 iPad Pro 11 Inch iPad 9.7 iPad Mini 6 5 4 3 Phone White Wide Compatibility: This tablet stand for desk can fit for 4 to 11 inch tablet, cell phone and E-reader with Max thickness of 0.55" (including its case). Compatible for Apple iPad 9.7 inch, iPad 10.2" 2019, iPad Pro 11-inch 2020, iPad mini 2 3 4 5 Wi-Fi, iPad Air 2, iPhone 13 12 11 Pro Max, iPhone 12 mini, iPhone and android phones. Lightweight & Minimalist Design: With a small size of 4.7" x 4.2", the tablet stand can be foldable and easy to slip into your pocket for travel. A perfect companion at home, in the office, kitchen, classroom or on the go Multi-Angle Adjustable: Adjust angles from 15° to 100° for the preferred viewing. This tablet holder for desk can hold your smartphone or tablet at a comfortable angle, ideal for watching videos, reading, recording, browsing, facetime call and more. Sturdy and Durable: Premium ABS material supports this ipad pro stand holder for desk durability in usage. Silicone pads on the bottom to protect your phone or tablet from sliding and scratches. What You Get: 2x UGREEN Ipad Holder Stand for business trip.',
  'GrandPad Senior Tablet (Renewed) with Phone Capabilities, 4G LTE, Wireless Charger, Stylus, 1 Month Premium Service Plan Included, Purchase A Plan at Activation MADE FOR SENIORS: The GrandPad is the ideal tablet & phone, all-in-one connectivity device for older adults. It has a closed network, so it keeps the older adult free of receiving any spam or robocalls. Its simple interface & easy connectivity makes it the perfect choice for families looking to stay connected in a safe & secure way. SERVICE PLAN NEEDED: 1 Month Included - A Monthly or Annual Service Plan can be purchased at Activation by calling GrandPad directly. Choose from our 599/prepaid yearly or 59/monthly (regularly 799/annual & 79/monthly) Service Plans. A Service Plan is needed to continue to have full access to all applications, 4G LTE, & 24/7/365 White Glove Support. If you opt out of GrandPad’s Service Plan there will be limited use and functionality of the GrandPad. 30-Day Risk Free Money Back Guarantee. This device must be activated with GrandPad, Inc and is not compatible with the Consumer Cellular (CCI) network. KEEPING FAMILIES CONNECTED: GrandPad is custom-made, has a senior-friendly interface, applications, 24/7/365 customer support, free companion applications for Android & iOS, & a private network to share & connect. 4G LTE CONNECTED TABLET: Built-in 4G LTE & is also wifi friendly. (Accessible with Premium Service Plan) Provides easy Internet Access & Phone Call & Video Call options, with no robocalls or spam. ACCESSIBILITY TOOLS: GrandPad’s user interface was developed for individuals with accessibility challenges. The icons are clear, clean, & concise. The screen is bright, and the front-facing speakers play audio and music loudly & clearly. Great option for those who have hearing, eyesight & dexterity issues. ACCESSORIES INCLUDED: A stylus, a durable case that keeps the tablet protected, and a wireless charger, which makes it effortless to keep this device powered.',
  "7inch Tablet for Kids Android 11 Tablets 3GB 32GB Parental Control Children Learning Toddler Tablet Shockproof Kickstand Case, GMS Certified, Google Tableta YouTube Netflix (Pink) ★[Best Kids-Friendly Compansion ] -With parental control mode, you can create and customize profiles for kids’accounts, hand-pick content for your kids, control screen time and ensure they are browsing safe websites. These security settings can be adjusted as kids grow with content tailored to their age. ★[A Full-feature Tablet for Kids] - This kids edition tablet has built-in a high-performance quad-core processor with stable Android 11 smooth System OS, 1024x600 IPS HD display, Wifi, Bluetooth, dual camera with flash, touch screen, 3GB RAM and 32GB ROM. You can expand the storage to 256GB of SD cards for storing photos, music, videos. A more stable Wifi module and a durable battery 3000mAh will offer you a better experience. ★[Free Kids APP & Games Pre-installed ] - COLORROOM Kids Tablet comes with a safe and funny iWawa Kid's software free pre-installed apps for Kids learning & playing, free kids app in the kids store, you can download different apps from the Google Play store. An ideal gift for birthday, Christmas, holiday season for kids or yourself. 【Exclusive Kid-Proof Case & Tablet Kickstand 】The specially designed case protects your kid's tablet against dust, bumps and drops. Risk-assured, you will get a brand-new one if the android tablet is crushed when it drops from the tab. At the same time, all the features are accessible with precise cut-outs of ports, cameras. A colorful and Stable stand on the back of the case allows toddlers to go hands-free for watching videos and video chatting. 【5 Years Quality Assurance】Customer satisfaction is always our first standard. If there is any problem with the use of kids learning tablet, please feel free to contact us, we will always here help you out within 24 hours . 180-days money-back and 5 years of life time worry-free protection .",
  'Tablet 10.1 Inch 2 in 1 Android Tablets with Keyboard Pen Mouse, Dual SIM Slot 4G Cellular,1.6Hz Octa-Core Processor, 4GB RAM 64GB ROM 13+5MP Camera WiFi Bluetooth, Google Tablet PC, GPS,OTG, 6000mAh 2022 Newest 4G Phone Tablet: The 10 inch Android 11 Tablet PC supports 4G network / cellular network and WIFI, so the tablet is a smartphone and a tablet at the same time. High Performance & Multi-Function : 10.1 inch IPS screen 1080P HD Display + Dual 4G Cellular sim slot (SIM CARD NOT PROVIDED),13+5MP camera with Flash Light, Support Phone call, Bluetooth,WIFI, GPS, 1080P Videos. Meets Reading, Photograph, Music, etc. Suitable for Most Life Scenarios. Long Lasting Battery: 10" Tablet PC Equipped with 6000mAh rechargeable battery for over 8 hours of mixed use. Enjoy reading, listening to music, watching movies, playing games, video calling or surfing the internet even when you travel. Large Storage: 4GB RAM+ internal 64GB ROM+expansion up to 128GB, plenty of memory to store videos, music, games and more file. Parental mode: Using Family Link downloaded from the Google Play Store enables parental control of the tablet, allowing children to use the tablet as well, works as kids Tablet.',
  "seenda Multi-Device Bluetooth Keyboard Compatible for iPad - Backlit Wireless Keyboard with Phone/Tablet Holder, Rechargeable Keyboard Compatible for iOS, Mac OS, Windows, Android Devices - Black Bluetooth Keyboard with Ability to Switch between 3 Devices -- Bluetooth 5.1 technology makes for a fast and simple connection. There are separate buttons for each connected devices to make Bluetooth pairing & switching between multiple devices as quick and easy as possible Wireless Keyboards with Build-in Phone & Tablet Holder Slot -- There is a slot across the top of the keyboard for holding a cell phone or tablet either vertically or horizontally, which makes typing on the phone/tablet easier since you can easily type and still see the screen Compact Light-up Keyboard Offers SEVEN LED color options -- Easy-to-see backlit keys with a choice of colors and adjustable brightness. Changing the backlit color of the keyboard is as easy as pressing the FN key + “Enter”key, pressing FN key + “Shift” key to adjust 3 different brightnesses Rechargeable Keyboards Equipped with USB-C Charging Port -- If you tired of changing batteries, this keyboard could be your choice, with build-in rechargeable battery, can be easily recharged with the USB-C charging cable included in package Silent Keyboard Provides Smooth and Responsive Typing -- The keys have a nice, soft feel under your fingers. Low profile & flat design ensures a smooth & responsive typing, cause your fingers don't get tangled up hitting keys they're not supposed to ONLY FOR BLUETOOTH-ENABLED DEVICES",
  "Universal Case for 9.5-10.5 inch Tablet, Chgdss for iPad 9.7/10.2/10.5 inch, Samsung Galaxy Tab A 10.1/Tab E 9.6 and More 9.5-10.5 inch Tablets, for All 9.5-10.5 inch Android Windows Tablet,Cute Dog Universal folio case for all 9 - 11 inch tablets, such as Notepad K10, Dragon Touch K10, A1X Plus, A1X, M10X, E97, A93; Vankyo MatrixPad S10, S21, S20, S30; NeuTab N9 Pro, N10, iR. ulu X1 Pro, X1s, PRITOM, ASIUR, ZONKO, Alldaymall, Polaroid, PolaTab, Feonal, ProntoTec, ValuePad VP112-10, Goldengulf, FastTouch, Tagital, DeerBrook, Simbans, Acer, Toshiba, Toshiba, RCA, iView, Dell, HP, etc. . (No rear camera hole; does not support automatic sleep/wake on any tablet) There are 4 PU plastic buckles that will hold your tablet very firmly so that your tablet won't fall and prevent it from falling. And it will not affect your use. Multiple slots able to set up multiple Interior card slots are designed for you to carry your business cards / bank cards / Wallet pocket provides to carry some notes or bucks while on the go. Stand Function: Two anti-slip grooves Multi-angle design to meet the needs of your multi-angle work for watching movie or typing. Made Premium Material of PU leather, protective smooth outer casing and sturdy exterior with soft microfiber interior keeps your iPad screen safe&sound, back cover provides best protection for your tablet.",
  "TECLAST Tablet 10 inch Android 12 Tablets, P25T 64GB ROM 1TB Expand Tablets, Android 12 3GB RAM Wi-Fi 6 Tablet PC, Tableta with 1.8Ghz 4-core CPU, 2.4g+5g WiFi, 10.1'' IPS Screen,Dual Cameras, Stereo 【Latest Android 12 tablet + GMS certification】The latest Android 12 smart operating system in 2022 simplifies system interaction design, optimizes the underlying code of the system, and makes tablet Android 12 run smoother and faster. make it possible. Further security and privacy improvements for Android 12 tablets give users a deeper understanding and control over the data applications access. The 10-inch tablet PC has passed Google's GMS certification. You can not only experience stable and smooth Google services, but also install your favorite third-party applications such as LINE/Netflix/YouTube/Facebook/Twitter. 【10.1 Inch IPS Display】 10.1 inch android tablet equipped with high resolution of 10.1-inch 1280*800 IPS display,comfortable 16:10 screen ratio for viewing video content. Sizing up to 10.1 inches, you get more space, best choice for movie and video viewing and site browsing. In addition, this 10 inch tablet with Digital Health and Parental Controls, you can analyze and control how your child is using their tablet to balance education and entertainment. The latest Android 12 tablet A 10-inch tablet suitable for children, parents and friends as an ideal Christmas, birthday, coming-of-age gift. 【Fast WiFi-6 tablet】 The TECLAST P25T tablet simultaneously supports 802.11 a/b/g/n/ac/ax Wi-Fi 6, more stable WiFi wireless signal, faster transmission speed, and more power saving for your wireless devices. The 10 inch tablet P25T uses 6th generation WiFi technology. Built-in dual-band WIFI chip, 5G WiFi and 2.4G WiFi are more stable. It features high-speed WIFI 6 network access, faster and smoother than WIFI 5. It is also equipped with Bluetooth 5.0. Bluetooth 5.0 brings you a shocking experience of low power wireless headphones. In addition, In addition, built-in 5000mah battery, so you can easily enjoy e-books, movies, dramas, and music while traveling or on a business trip. 【4 core tablet & More Storage】The Android 12 tablet is equipped with Allwinner A133 and is equipped with a 1.8GHz 4-core CPU for smoother operation. Equipped with 3GB RAM and 64GB ROM, MicroSD card slot (expandable up to 1TB/FAT32 format, sold separately) for more memory possibilities. By four A53 processors with IMG PowerVR GE8300 graphics processors. Display colors and details have been enhanced using intelligent algorithms to deliver stunning visuals and detailed video playback for games. The P25T Android tablet comes with a convenient USB Type C +3.5mm headphone port to meet your various needs. 【Ideal Choice For Daily Use】 We guaranteed coverage of 1-year warranty for the P25T Android 12 tablet. In the unlikely event that the product is defective, please contact us through your Amazon purchase history. We will do our best to satisfy our customers. This WiFi tablet has excellent performance, stylish appearance, large memory to meet Kids and Family daily leisure needs. Good teen tablet for Reading, Photograph, videos, Music, social Apps etc.",
  "ANTEMPER Tablet 10.1 Inch Android 11 Tablets with 4G RAM, 64GB ROM, 4G LTE, Octa-Core Chip, Keyboard，Tablet Case, 13MP Camera, Bluetooth, WiFi, GPS, Dual Sim Card Slot, HD Touchscreen, (White) Let the Speed Blow You Away: Equipped with 4GB RAM & 64GB ROM, the octa-core CPU operates at up to 1.6 GHz, 60Hz refresh rate and 390Hz touch sampling rate. The Powerful Android 10 tablet provides + 46% faster processing speed than Quad-Core tablet, the octa-core chip works seamlessly with the CPU and GPU to achieve an efficient balance between battery life and performance. The latest version of Android 11.0 for 4G LTE mobile tablet:Tablet is equipped with 2022 latest version of Android 11 OS,Octa-core processor and 1.6GHz.Mobile tablet supports 4G/3G/2G network,WiFi,GPS,Bluetooth 5.0,OTG,FM,and has two SIM card slots.After inserting SIM card,it becomes an Android phone.You can make calls and send messages to your friends at any time.Even if you don't have SIM card,you can connect to Wi-Fi and hotspots. 4GB RAM + 64GB ROM + Value-added Multi-Accessories + Octa-Core Processor:4GB RAM and 64GB ROM storage, expandable up to 128GB with SD card.Octa-core processor is perfect for running many apps smoothly.Equipped with Bluetooth keyboard,mouse and capacitive stylus and many other accessories,the handheld tablet instantly turns into a mobile work tablet,allowing you to surf the Internet,watch movies,work,take notes or participate in class remotely. GMS Certified and Full-featured Tablet: More security and more privacy with GMS certified system. This tablet can be unlocked with Face ID and PIN code and has split-screen function for efficient use. You can log in to your -account and control this tablet remotely via Family Link app for parents. You have full access to Play Store to download Netflix, Facebook, YouTube, Skype and other apps. 13MP+5MP dual camera + 1080 FHD IPS + 6000mAh big battery: 13MP rear camera can leave exquisite landscapes and 5MP front camera has powerful beauty camera function. And 1280*800 IPS screen and excellent dual speakers provide 1080p FHD quality video image and clearer sound quality. With a large built-in 6000mAh battery, it has longer runtime and standby time, so you can enjoy up to 13 to 15 hours entertainment.",
  'Keyboard Case for Kindle Fire HD 10/HD 10 Plus Table 2021 (11th Generation) 10.1 inch, Slim Folding Stand Cover with Wireless Bluetooth Keyboard, Fire Tablet Keyboard Case with Auto Wake/Sleep - Blue ✔【 Compatibilitny】Specifically designed for Amazon All-New Kinde Fire HD 10 Tablet and Fire HD 10 Plus Tablet 10.1 Inch. ( Not For Fire HD 10 tablet 7th and 9th Generation 2017 and 2019 Releases) Please check the tablet models before purchasing. ✔【 Auto Wake/Sleep & Long Lasting Battery】 Reacts instantly when opening and closing the cover to maximize battery life, which helps you save precious battery life. 220 mAh battery provides up to half year of regular use between charges. So you don’t have to drag along extra cords for charging. Charging time: 2-3 hours, battery running:> 100 hours. ✔【 Detachable Comfortable & Smooth Keyboard】The Fire tablet keyboard features a full row of shortcut keys for one-tap access to popular functions including volume and media controls, brightness levels, and more. Decades of MMK expertise ensure you a comfortable, quiet, and smooth typing experience, letting you work comfortably at any time of day. The Fire HD 10 keyboard case uses a stable and mature Bluetooth technology, up to 10 meters, so you can easily use it at home or in the office, simple and stable. ✔【 Multi-Viewing Angles and Anti-Slip Design】Three dents on the case for propping up the tablet into three different viewing angles in landscape mode. Perfect for working, writing, or watching videos. This slim keyboard case will turn your Fire HD 10 tablet into a powerful laptop any time you’d want it, lightweight and portable. You enjoy your kindle tablet a little more even when you’re out and about! ✔【Premium Material & Precise Cutout】Made of durable TPU leather exterior that provides total full body protection. The cut-outs for the camera, speakers, and volume buttons all line up perfectly. All buttons are easily accessed. Pay attention that this protective case has a unique cutout that is specially prepared for the microphone, which can ensure that you get a perfect exhaled sound quality when you make a call. ✔【Rich Accessories & Excellent Customer Service】 1 x fire hd 10 tablet case with keyboard, 1x usb charging cord, 1 x user guide. In addition, free lifetime technical support and a 12-month manufacturer’s warranty can give you peace of mind about your purchase. Click “Add to Cart” now – You won’t regret it!',
  'PEYOU Tablet Holder, Adjustable 360 Degree Rotation Foldable Tablet Stand for Bed with 4 Cord Clips, Pefect for iPad/iPhone/Kindle/M-Switch, or Other 4.5-12.9" Device Material upgrade & super stability: Equipped with three sections of high-quality carbon steel bionic mechanical cantilever, the stability is increased by 100%. iPad Holder for bed is equipped with a professional anti-shock spring, which can bear a weight of 1.5 kg, and the support is firm and does not sag. Girls can adjust it with one hand, and can watch movies comfortably while lying on the bed. Multi-angle adjustment: The iPad stand with 4 joints and 360-degree adjustable ball head allows you to adjust the angle more freely to operate the tablet in your favorite posture. 6 adjustable nodes to secure your device where you want it, such as relaxing while watching videos, web conferencing, working from home and online classes. Base for vertical and horizontal use:The base is equipped with two jacks, which can realize the vertical and horizontal use of the stand, and it is equipped with a sponge pad, which will not damage your headboard, and has high stability during use. The base can firmly clamp the table, bedside and other installation surfaces by about 40mm. Installation requires no tools or holes. Note: The bed board thickness needs to be less than 6. 5cm/2.56 inch. Wide Compatibility: Universally compatible with devices between 4.5 inches and 12.9 inches. This stand is perfect for mounting iPad Pro 12.9" or 10.7" or 9.7"/iPad Air, iPad Mini and all tablets 7-13" sizes as well as all iPhones and N-Switch and Amazon Kindle Fire. Convenient charging, high-quality after-sales: The package is equipped with 4 cable clips, which can realize the use of the bracket while charging, bringing convenience to your life. If you have any questions, please feel free to contact us by email. We will reply within 24 hours. If there is any problem with the product, you will get a full refund. Best gift for wife, friend or colleague.',

Hybrid Search with weighted RRF

In [65]:
def retrieve_data(query, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-hybrid-search",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                limit=20
            ),
            Prefetch(
                query=Document(
                    text=query,
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=20
            )
        ],
        query=models.RrfQuery(rrf=models.Rrf(weights=[3,1])),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    retrieved_context_ratings = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_description"])
        similarity_scores.append(result.score)
        retrieved_context_ratings.append(result.payload["average_rating"])

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
        "retrieved_context_ratings": retrieved_context_ratings
    }

In [66]:
results = retrieve_data("Can I get a tablet?", k=20)

In [67]:
results

{'retrieved_context_ids': ['B0B7QL4FMN',
  'B0C4KCQB19',
  'B09MKYBJT6',
  'B07FMF2L6B',
  'B0BN7JTB5N',
  'B0B3QGL9C9',
  'B0BCFYCXRH',
  'B0BCDYMF5L',
  'B0C1TWNBGD',
  'B0BQ1ZVF2C',
  'B0BHP1HMK2',
  'B0BJPTYFK9',
  'B0BKZN3N6L',
  'B0B7MR7WS7',
  'B0C1P9YW5R',
  'B0BDD6BC6Y',
  'B0BTPG4XHH',
  'B09RN3KN5C',
  'B0C6QXGW5S',
  'B09SFX1KYC'],
 'retrieved_context': ['GrandPad Senior Tablet (Renewed) with Phone Capabilities, 4G LTE, Wireless Charger, Stylus, 1 Month Premium Service Plan Included, Purchase A Plan at Activation MADE FOR SENIORS: The GrandPad is the ideal tablet & phone, all-in-one connectivity device for older adults. It has a closed network, so it keeps the older adult free of receiving any spam or robocalls. Its simple interface & easy connectivity makes it the perfect choice for families looking to stay connected in a safe & secure way. SERVICE PLAN NEEDED: 1 Month Included - A Monthly or Annual Service Plan can be purchased at Activation by calling GrandPad directly. Choose from our 599/prepaid yearly or 59/monthly (regularly 799/annual & 79/monthly) Service Plans. A Service Plan is needed to continue to have full access to all applications, 4G LTE, & 24/7/365 White Glove Support. If you opt out of GrandPad’s Service Plan there will be limited use and functionality of the GrandPad. 30-Day Risk Free Money Back Guarantee. This device must be activated with GrandPad, Inc and is not compatible with the Consumer Cellular (CCI) network. KEEPING FAMILIES CONNECTED: GrandPad is custom-made, has a senior-friendly interface, applications, 24/7/365 customer support, free companion applications for Android & iOS, & a private network to share & connect. 4G LTE CONNECTED TABLET: Built-in 4G LTE & is also wifi friendly. (Accessible with Premium Service Plan) Provides easy Internet Access & Phone Call & Video Call options, with no robocalls or spam. ACCESSIBILITY TOOLS: GrandPad’s user interface was developed for individuals with accessibility challenges. The icons are clear, clean, & concise. The screen is bright, and the front-facing speakers play audio and music loudly & clearly. Great option for those who have hearing, eyesight & dexterity issues. ACCESSORIES INCLUDED: A stylus, a durable case that keeps the tablet protected, and a wireless charger, which makes it effortless to keep this device powered.',
  "7inch Tablet for Kids Android 11 Tablets 3GB 32GB Parental Control Children Learning Toddler Tablet Shockproof Kickstand Case, GMS Certified, Google Tableta YouTube Netflix (Pink) ★[Best Kids-Friendly Compansion ] -With parental control mode, you can create and customize profiles for kids’accounts, hand-pick content for your kids, control screen time and ensure they are browsing safe websites. These security settings can be adjusted as kids grow with content tailored to their age. ★[A Full-feature Tablet for Kids] - This kids edition tablet has built-in a high-performance quad-core processor with stable Android 11 smooth System OS, 1024x600 IPS HD display, Wifi, Bluetooth, dual camera with flash, touch screen, 3GB RAM and 32GB ROM. You can expand the storage to 256GB of SD cards for storing photos, music, videos. A more stable Wifi module and a durable battery 3000mAh will offer you a better experience. ★[Free Kids APP & Games Pre-installed ] - COLORROOM Kids Tablet comes with a safe and funny iWawa Kid's software free pre-installed apps for Kids learning & playing, free kids app in the kids store, you can download different apps from the Google Play store. An ideal gift for birthday, Christmas, holiday season for kids or yourself. 【Exclusive Kid-Proof Case & Tablet Kickstand 】The specially designed case protects your kid's tablet against dust, bumps and drops. Risk-assured, you will get a brand-new one if the android tablet is crushed when it drops from the tab. At the same time, all the features are accessible with precise cut-outs of ports, cameras. A colorful and Stable stand on the back of the case allows toddlers to go hands-free for watching videos and video chatting. 【5 Years Quality Assurance】Customer satisfaction is always our first standard. If there is any problem with the use of kids learning tablet, please feel free to contact us, we will always here help you out within 24 hours . 180-days money-back and 5 years of life time worry-free protection .",
  'Tablet 10.1 Inch 2 in 1 Android Tablets with Keyboard Pen Mouse, Dual SIM Slot 4G Cellular,1.6Hz Octa-Core Processor, 4GB RAM 64GB ROM 13+5MP Camera WiFi Bluetooth, Google Tablet PC, GPS,OTG, 6000mAh 2022 Newest 4G Phone Tablet: The 10 inch Android 11 Tablet PC supports 4G network / cellular network and WIFI, so the tablet is a smartphone and a tablet at the same time. High Performance & Multi-Function : 10.1 inch IPS screen 1080P HD Display + Dual 4G Cellular sim slot (SIM CARD NOT PROVIDED),13+5MP camera with Flash Light, Support Phone call, Bluetooth,WIFI, GPS, 1080P Videos. Meets Reading, Photograph, Music, etc. Suitable for Most Life Scenarios. Long Lasting Battery: 10" Tablet PC Equipped with 6000mAh rechargeable battery for over 8 hours of mixed use. Enjoy reading, listening to music, watching movies, playing games, video calling or surfing the internet even when you travel. Large Storage: 4GB RAM+ internal 64GB ROM+expansion up to 128GB, plenty of memory to store videos, music, games and more file. Parental mode: Using Family Link downloaded from the Google Play Store enables parental control of the tablet, allowing children to use the tablet as well, works as kids Tablet.',
  "Universal Case for 9.5-10.5 inch Tablet, Chgdss for iPad 9.7/10.2/10.5 inch, Samsung Galaxy Tab A 10.1/Tab E 9.6 and More 9.5-10.5 inch Tablets, for All 9.5-10.5 inch Android Windows Tablet,Cute Dog Universal folio case for all 9 - 11 inch tablets, such as Notepad K10, Dragon Touch K10, A1X Plus, A1X, M10X, E97, A93; Vankyo MatrixPad S10, S21, S20, S30; NeuTab N9 Pro, N10, iR. ulu X1 Pro, X1s, PRITOM, ASIUR, ZONKO, Alldaymall, Polaroid, PolaTab, Feonal, ProntoTec, ValuePad VP112-10, Goldengulf, FastTouch, Tagital, DeerBrook, Simbans, Acer, Toshiba, Toshiba, RCA, iView, Dell, HP, etc. . (No rear camera hole; does not support automatic sleep/wake on any tablet) There are 4 PU plastic buckles that will hold your tablet very firmly so that your tablet won't fall and prevent it from falling. And it will not affect your use. Multiple slots able to set up multiple Interior card slots are designed for you to carry your business cards / bank cards / Wallet pocket provides to carry some notes or bucks while on the go. Stand Function: Two anti-slip grooves Multi-angle design to meet the needs of your multi-angle work for watching movie or typing. Made Premium Material of PU leather, protective smooth outer casing and sturdy exterior with soft microfiber interior keeps your iPad screen safe&sound, back cover provides best protection for your tablet.",
  'UGREEN 2 Pack Tablet Stand Holder Adjustable Desktop Portable Stand Home Office Desk Accessories Compatible with iPad 10.2 iPad Pro 11 Inch iPad 9.7 iPad Mini 6 5 4 3 Phone White Wide Compatibility: This tablet stand for desk can fit for 4 to 11 inch tablet, cell phone and E-reader with Max thickness of 0.55" (including its case). Compatible for Apple iPad 9.7 inch, iPad 10.2" 2019, iPad Pro 11-inch 2020, iPad mini 2 3 4 5 Wi-Fi, iPad Air 2, iPhone 13 12 11 Pro Max, iPhone 12 mini, iPhone and android phones. Lightweight & Minimalist Design: With a small size of 4.7" x 4.2", the tablet stand can be foldable and easy to slip into your pocket for travel. A perfect companion at home, in the office, kitchen, classroom or on the go Multi-Angle Adjustable: Adjust angles from 15° to 100° for the preferred viewing. This tablet holder for desk can hold your smartphone or tablet at a comfortable angle, ideal for watching videos, reading, recording, browsing, facetime call and more. Sturdy and Durable: Premium ABS material supports this ipad pro stand holder for desk durability in usage. Silicone pads on the bottom to protect your phone or tablet from sliding and scratches. What You Get: 2x UGREEN Ipad Holder Stand for business trip.',
  "ANTEMPER Tablet 10.1 Inch Android 11 Tablets with 4G RAM, 64GB ROM, 4G LTE, Octa-Core Chip, Keyboard，Tablet Case, 13MP Camera, Bluetooth, WiFi, GPS, Dual Sim Card Slot, HD Touchscreen, (White) Let the Speed Blow You Away: Equipped with 4GB RAM & 64GB ROM, the octa-core CPU operates at up to 1.6 GHz, 60Hz refresh rate and 390Hz touch sampling rate. The Powerful Android 10 tablet provides + 46% faster processing speed than Quad-Core tablet, the octa-core chip works seamlessly with the CPU and GPU to achieve an efficient balance between battery life and performance. The latest version of Android 11.0 for 4G LTE mobile tablet:Tablet is equipped with 2022 latest version of Android 11 OS,Octa-core processor and 1.6GHz.Mobile tablet supports 4G/3G/2G network,WiFi,GPS,Bluetooth 5.0,OTG,FM,and has two SIM card slots.After inserting SIM card,it becomes an Android phone.You can make calls and send messages to your friends at any time.Even if you don't have SIM card,you can connect to Wi-Fi and hotspots. 4GB RAM + 64GB ROM + Value-added Multi-Accessories + Octa-Core Processor:4GB RAM and 64GB ROM storage, expandable up to 128GB with SD card.Octa-core processor is perfect for running many apps smoothly.Equipped with Bluetooth keyboard,mouse and capacitive stylus and many other accessories,the handheld tablet instantly turns into a mobile work tablet,allowing you to surf the Internet,watch movies,work,take notes or participate in class remotely. GMS Certified and Full-featured Tablet: More security and more privacy with GMS certified system. This tablet can be unlocked with Face ID and PIN code and has split-screen function for efficient use. You can log in to your -account and control this tablet remotely via Family Link app for parents. You have full access to Play Store to download Netflix, Facebook, YouTube, Skype and other apps. 13MP+5MP dual camera + 1080 FHD IPS + 6000mAh big battery: 13MP rear camera can leave exquisite landscapes and 5MP front camera has powerful beauty camera function. And 1280*800 IPS screen and excellent dual speakers provide 1080p FHD quality video image and clearer sound quality. With a large built-in 6000mAh battery, it has longer runtime and standby time, so you can enjoy up to 13 to 15 hours entertainment.",
  "TECLAST Tablet 10 inch Android 12 Tablets, P25T 64GB ROM 1TB Expand Tablets, Android 12 3GB RAM Wi-Fi 6 Tablet PC, Tableta with 1.8Ghz 4-core CPU, 2.4g+5g WiFi, 10.1'' IPS Screen,Dual Cameras, Stereo 【Latest Android 12 tablet + GMS certification】The latest Android 12 smart operating system in 2022 simplifies system interaction design, optimizes the underlying code of the system, and makes tablet Android 12 run smoother and faster. make it possible. Further security and privacy improvements for Android 12 tablets give users a deeper understanding and control over the data applications access. The 10-inch tablet PC has passed Google's GMS certification. You can not only experience stable and smooth Google services, but also install your favorite third-party applications such as LINE/Netflix/YouTube/Facebook/Twitter. 【10.1 Inch IPS Display】 10.1 inch android tablet equipped with high resolution of 10.1-inch 1280*800 IPS display,comfortable 16:10 screen ratio for viewing video content. Sizing up to 10.1 inches, you get more space, best choice for movie and video viewing and site browsing. In addition, this 10 inch tablet with Digital Health and Parental Controls, you can analyze and control how your child is using their tablet to balance education and entertainment. The latest Android 12 tablet A 10-inch tablet suitable for children, parents and friends as an ideal Christmas, birthday, coming-of-age gift. 【Fast WiFi-6 tablet】 The TECLAST P25T tablet simultaneously supports 802.11 a/b/g/n/ac/ax Wi-Fi 6, more stable WiFi wireless signal, faster transmission speed, and more power saving for your wireless devices. The 10 inch tablet P25T uses 6th generation WiFi technology. Built-in dual-band WIFI chip, 5G WiFi and 2.4G WiFi are more stable. It features high-speed WIFI 6 network access, faster and smoother than WIFI 5. It is also equipped with Bluetooth 5.0. Bluetooth 5.0 brings you a shocking experience of low power wireless headphones. In addition, In addition, built-in 5000mah battery, so you can easily enjoy e-books, movies, dramas, and music while traveling or on a business trip. 【4 core tablet & More Storage】The Android 12 tablet is equipped with Allwinner A133 and is equipped with a 1.8GHz 4-core CPU for smoother operation. Equipped with 3GB RAM and 64GB ROM, MicroSD card slot (expandable up to 1TB/FAT32 format, sold separately) for more memory possibilities. By four A53 processors with IMG PowerVR GE8300 graphics processors. Display colors and details have been enhanced using intelligent algorithms to deliver stunning visuals and detailed video playback for games. The P25T Android tablet comes with a convenient USB Type C +3.5mm headphone port to meet your various needs. 【Ideal Choice For Daily Use】 We guaranteed coverage of 1-year warranty for the P25T Android 12 tablet. In the unlikely event that the product is defective, please contact us through your Amazon purchase history. We will do our best to satisfy our customers. This WiFi tablet has excellent performance, stylish appearance, large memory to meet Kids and Family daily leisure needs. Good teen tablet for Reading, Photograph, videos, Music, social Apps etc.",
  "DUODUOGO Tablet 2 in 1, Tablet 10.1 inch Android 9 with Keyboard, Mouse Stylus Case, 3GB + 32GB(128GB Expand) 4G SIM+WiFi, Quad-Core Processor, HD Touch Screen, Google GMS Certified, DGO-A38 (Black) FAST AND RESPONSIVE PERFORMANCE: Equipped with the powerful and energy-saving 64 bit Quad-core processor 1.6GHz, RAM 4GB your tablet enables quick app launches and run smoothly. EXCELLENT HD DISPLAY: The 10.1 inch HD IPS Display with 1280*800 Resolution that stays clear in any light, which presents a bright display with vivid colors for a more true-to-life viewing experience from all angles. Support T mobile band, support LAN wireless screen casting. Both charging and data transmission would be supported via micro USB. COMPLETE PERIPHERAL ACCESSORIES: The tablet case built-in double magnet design, automatic adsorption, and can be used as a folding stand for tablet computers. Simple and stylish unlimited Bluetooth keyboard and mouse make your operation more convenient. Dual-purpose Touch screen pen is both a capacitor pen and a ballpoint pen. The USB LED light that can rotate 360°allows you to use the tablet comfortably at night. LONG LASTING ENTERTAINMENT:Large capacity 8000mAh lithium polymer battery together with the low power consumption CPU enable you enjoy up to 8 hours' mixed use of reading, watching TV shows and movie, surfing the web, listen to music, shopping, playing games, etc. MORE SOTRAGE SPACE: DUODUOGO P8 tablet has 64GB ROM, You can easily expand the storege space to 128GB with Micro SD Card (not included). You can also download more apps you like in the app store, Such as Netflix, Facebook, Youtube, Instagram, WhatsAPP, NF, Hulu TikTok etc.",
  'Android Tablet, 10 Inch Android 12 Tablet, 6GB RAM 64GB ROM, 1TB Expand, Android Tablet with 8000mAh Battery, Dual Camera, 5G WiFi, Bluetooth, FHD IPS Touch Screen, GPS, Google GMS Certified 【5G WiFi & 8000mAh High Capacity Battery】 This Android Tablet has a 5G WiFi module, which means it can connect to the internet faster than most other tablet with older WiFi modules. This feature allows for faster download and upload speeds, which is great for streaming movies, playing online games, and working remotely. The Tablet has an 8000 mAh battery, which is a high capacity battery that can last for a long time. This feature is ideal for people who frequently go on long trips and want to stay connected to the internet without having to worry about their tablet\'s battery dying quickly 【6GB RAM 64GB ROM & Excellent Processor】 The Android 12 Tablet is equipped with an 1.8GHz excellent processor, 6GB(4GB+2GB) RAM and 64GB ROM, which means it can run apps and games quickly and smoothly without any lag. This feature is ideal for people who like to play games, run multiple apps at once, or use android tablet for work 【10.1" FHD IPS Screen & Dual Camera】 The 10.1 inch tablet has an G+G FHD IPS screen, which means it can display high-quality images and videos with great clarity and color accuracy. This feature is ideal for people who like to watch movies, play games, or work on a tablet for extended periods of time. Dual camera (8MP Rear, 5MP Front) with auto focus function, you can take beautiful photos or make smooth video conversations 【1TB Huge Capacity Storage & Google GMS Certification】 This Tablets is equipped with 64GB ROM Built-in memory, supports 1TB (1024GB) capacity expansion, includes a micro SD slot, lightweight but excellent, allows you to download a large number of applications from Google Play Store and have fun with them. The android tablet has passed the Google GMS certification. You have full access to the latest Google service, such as Google Play, WhatsApp, G-mail, Skype, Disney+, Netflix, YouTube, ZOOM, Google Assistant and more brilliant apps 【5-year Warranty】 Our 10 inch tablet offers a 5-year warranty and Lifetime customer service, If you have any questions, please contact us, our customer service manager will reply you within 24 hours. Package Includes：1 x Tablet PC, 1 x High-quality Tablet Case, 1 x Screen Protector, 1 x OTG Cable, 1 x Charging Cable, 1 x User Manual',
  'PEYOU Tablet Holder, Adjustable 360 Degree Rotation Foldable Tablet Stand for Bed with 4 Cord Clips, Pefect for iPad/iPhone/Kindle/M-Switch, or Other 4.5-12.9" Device Material upgrade & super stability: Equipped with three sections of high-quality carbon steel bionic mechanical cantilever, the stability is increased by 100%. iPad Holder for bed is equipped with a professional anti-shock spring, which can bear a weight of 1.5 kg, and the support is firm and does not sag. Girls can adjust it with one hand, and can watch movies comfortably while lying on the bed. Multi-angle adjustment: The iPad stand with 4 joints and 360-degree adjustable ball head allows you to adjust the angle more freely to operate the tablet in your favorite posture. 6 adjustable nodes to secure your device where you want it, such as relaxing while watching videos, web conferencing, working from home and online classes. Base for vertical and horizontal use:The base is equipped with two jacks, which can realize the vertical and horizontal use of the stand, and it is equipped with a sponge pad, which will not damage your headboard, and has high stability during use. The base can firmly clamp the table, bedside and other installation surfaces by about 40mm. Installation requires no tools or holes. Note: The bed board thickness needs to be less than 6. 5cm/2.56 inch. Wide Compatibility: Universally compatible with devices between 4.5 inches and 12.9 inches. This stand is perfect for mounting iPad Pro 12.9" or 10.7" or 9.7"/iPad Air, iPad Mini and all tablets 7-13" sizes as well as all iPhones and N-Switch and Amazon Kindle Fire. Convenient charging, high-quality after-sales: The package is equipped with 4 cable clips, which can realize the use of the bracket while charging, bringing convenience to your life. If you have any questions, please feel free to contact us by email. We will reply within 24 hours. If there is any problem with the product, you will get a full refund. Best gift for wife, friend or colleague.',